import type { Metadata } from "next";
import { ArrowLeft, Bell, Clock3, MapPin, Pencil, Repeat2, Tag } from "lucide-react";
import Link from "next/link";

import { archiveCalendarEvent } from "@/features/calendar/actions";
import { formatCalendarDate, formatCalendarTime } from "@/features/calendar/dates";
import { getNativeCalendarEvent } from "@/features/calendar/queries";
import { expandNativeEvent } from "@/features/calendar/native-recurrence";

export const metadata: Metadata = { title: "Event details" };

export default async function CalendarEventPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ occurrence?: string; success?: string; error?: string }> }) {
  const { id } = await params; const query = await searchParams;
  const { event, timeZone } = await getNativeCalendarEvent(id);
  const occurrence = query.occurrence && event.recurrenceFrequency ? expandNativeEvent(event, { start: query.occurrence, end: query.occurrence }).find((item) => item.recurrence?.occurrenceDate === query.occurrence) : null;
  const displayStart = occurrence?.start ?? (event.allDay ? event.startDate! : event.startsAt!); const displayEnd = occurrence?.end ?? (event.allDay ? event.endDate! : event.endsAt!);
  const timing = event.allDay ? `${formatCalendarDate(displayStart)}${displayEnd !== displayStart ? ` – ${formatCalendarDate(displayEnd)}` : ""} · All day` : `${new Intl.DateTimeFormat("en-CA", { month: "short", day: "numeric", year: "numeric", timeZone }).format(new Date(displayStart))} · ${formatCalendarTime(displayStart, timeZone)} – ${formatCalendarTime(displayEnd, timeZone)}`;
  const reminderLabel = (minutes:number) => minutes===0?"At event time":minutes<60?`${minutes} minutes before`:minutes===60?"1 hour before":minutes===1440?"1 day before":"1 week before";
  return <div className="mx-auto max-w-2xl space-y-6"><Link className="inline-flex min-h-10 items-center gap-2 text-sm font-semibold text-primary" href="/calendar"><ArrowLeft className="size-4" /> Back to Calendar</Link>{query.success ? <p className="rounded-lg bg-success/10 p-3 text-sm text-success" role="status">{query.success}</p> : null}{query.error ? <p className="rounded-lg bg-destructive/10 p-3 text-sm text-destructive" role="alert">{query.error}</p> : null}<article className="rounded-2xl border bg-card p-6 shadow-sm sm:p-8"><p className="text-sm font-semibold text-primary">Native Calendar {event.recurrenceFrequency ? "series" : "event"}</p><h1 className="mt-2 text-3xl font-bold tracking-tight">{event.title}</h1><div className="mt-6 space-y-4 text-sm"><p className="flex gap-3"><Clock3 className="size-5 shrink-0 text-primary" /> {timing}</p>{event.recurrenceFrequency ? <p className="flex gap-3 capitalize"><Repeat2 className="size-5 shrink-0 text-primary" /> Repeats {event.recurrenceFrequency}{event.recurrenceUntil ? ` through ${formatCalendarDate(event.recurrenceUntil)}` : ""}{event.recurrenceTimezone ? ` · ${event.recurrenceTimezone}` : ""}</p> : null}{event.reminderOffsets.length ? <p className="flex gap-3"><Bell className="size-5 shrink-0 text-primary" /> {event.reminderOffsets.map(reminderLabel).join(", ")} <span className="text-muted-foreground">(configuration only)</span></p> : null}{event.eventType ? <p className="flex gap-3 capitalize"><Tag className="size-5 shrink-0 text-primary" /> {event.eventType}</p> : null}{event.location ? <p className="flex gap-3"><MapPin className="size-5 shrink-0 text-primary" /> {event.location}</p> : null}{event.description ? <p className="border-t pt-5 leading-7 text-muted-foreground">{event.description}</p> : null}</div>{event.recurrenceFrequency ? <p className="mt-6 rounded-lg bg-accent/40 p-3 text-sm text-muted-foreground">Editing or archiving affects the entire series. Occurrence exceptions are deferred until they have a proper override model.</p> : null}<div className="mt-8 flex flex-col gap-3 border-t pt-5 sm:flex-row"><Link className="inline-flex min-h-11 items-center justify-center gap-2 rounded-lg bg-primary px-4 text-sm font-semibold text-primary-foreground" href={`/calendar/events/${id}/edit`}><Pencil className="size-4" /> Edit {event.recurrenceFrequency ? "series" : "event"}</Link><form action={archiveCalendarEvent}><input name="id" type="hidden" value={id} /><button className="min-h-11 w-full rounded-lg border border-destructive/30 px-4 text-sm font-semibold text-destructive hover:bg-destructive/10" type="submit">Archive {event.recurrenceFrequency ? "series" : "event"}</button></form></div></article></div>;
}
