import Link from "next/link";
import { TaskActivityChart } from "@/features/analytics/analytics-charts";
import { getTaskDeepAnalytics } from "@/features/analytics/deep-service";
import { AnalyticsRangeControls, AnalyticsSectionNav } from "@/features/analytics/range-controls";
import { formatEffort } from "@/features/tasks/task-service";

export const metadata = { title: "Task Analytics" };
const panel = "rounded-2xl border bg-card p-5 shadow-sm sm:p-6"; type Query = { range?: string | string[]; from?: string | string[]; to?: string | string[] };

export default async function TaskAnalyticsPage({ searchParams }: { searchParams: Promise<Query> }) {
  const data = await getTaskDeepAnalytics(await searchParams);
  return <div className="space-y-7"><header><Link className="text-sm font-semibold text-primary" href="/analytics">← Analytics overview</Link><h1 className="mt-2 text-3xl font-bold">Task analytics</h1><p className="mt-2 text-sm text-muted-foreground">Transparent lifecycle, deadline, priority, and effort metrics without a productivity score.</p></header><AnalyticsSectionNav active="tasks"/><AnalyticsRangeControls basePath="/analytics/tasks" range={data.range} selection={data.rangeSelection} timeZone={data.timeZone}/>
    <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["Created in range",data.created],["Completed in range",data.completed],["Currently overdue",data.currentlyOverdue],["Active without due date",data.activeNoDueDate]].map(([label,value]) => <article className="rounded-xl border bg-card p-4" key={label}><p className="text-xs font-bold uppercase text-muted-foreground">{label}</p><p className="mt-2 text-2xl font-bold">{value}</p></article>)}</section>
    <section className={panel}><div className="flex justify-between gap-3"><div><h2 className="text-xl font-bold">Created and completed</h2><p className="text-sm text-muted-foreground">Uses authoritative creation and completion timestamps.</p></div><Link className="text-sm font-semibold text-primary" href="/tasks">View Tasks</Link></div><TaskActivityChart data={data.trend}/></section>
    <section className="grid gap-6 lg:grid-cols-2"><div className={panel}><h2 className="text-xl font-bold">Deadline outcomes</h2><p className="text-sm text-muted-foreground">Only completed Tasks with an actual due date or time are eligible.</p><div className="mt-4 grid grid-cols-3 gap-3"><article className="rounded-xl border p-3"><p className="text-2xl font-bold">{data.deadline.eligible}</p><p className="text-xs text-muted-foreground">Eligible</p></article><article className="rounded-xl border p-3"><p className="text-2xl font-bold">{data.deadline.onTime}</p><p className="text-xs text-muted-foreground">On/before due</p></article><article className="rounded-xl border p-3"><p className="text-2xl font-bold">{data.deadline.late}</p><p className="text-xs text-muted-foreground">Completed late</p></article></div></div><div className={panel}><h2 className="text-xl font-bold">Completion time</h2>{data.medianCompletionMinutes === null ? <p className="mt-4 text-sm text-muted-foreground">Not enough completed Task timestamps in this range.</p> : <><p className="mt-4 text-3xl font-bold">{formatEffort(data.medianCompletionMinutes)}</p><p className="text-sm text-muted-foreground">Median creation-to-completion time across {data.completionDurationSamples} Task{data.completionDurationSamples === 1 ? "" : "s"}.</p></>}</div></section>
    <section className={panel}><h2 className="text-xl font-bold">Priority</h2><p className="text-sm text-muted-foreground">Priority is user-entered and never inferred from content.</p><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[480px] text-left text-sm"><thead className="text-xs uppercase text-muted-foreground"><tr><th>Priority</th><th>Created</th><th>Completed</th><th>Active now</th></tr></thead><tbody>{data.priorities.map((item) => <tr className="border-t" key={item.priority}><td className="py-3 font-semibold capitalize">{item.priority}</td><td>{item.created}</td><td>{item.completed}</td><td>{item.active}</td></tr>)}</tbody></table></div></section>
    <section className={panel}><h2 className="text-xl font-bold">Estimated effort coverage</h2><div className="mt-4 grid gap-3 sm:grid-cols-3"><article className="rounded-xl border p-4"><p className="text-sm text-muted-foreground">Completed estimated effort</p><p className="mt-1 text-2xl font-bold">{formatEffort(data.completedEffortMinutes) ?? "0 min"}</p></article><article className="rounded-xl border p-4"><p className="text-sm text-muted-foreground">Coverage</p><p className="mt-1 text-2xl font-bold">{data.effortCoverage.estimated} / {data.effortCoverage.completed}</p><p className="text-xs text-muted-foreground">Completed Tasks with estimates</p></article><article className="rounded-xl border p-4"><p className="text-sm text-muted-foreground">Median estimate</p><p className="mt-1 text-2xl font-bold">{data.medianEstimatedMinutes === null ? "Not enough data" : formatEffort(data.medianEstimatedMinutes)}</p></article></div></section>
  </div>;
}
