import type { Metadata } from "next";
import Link from "next/link";
import { ArrowDownLeft, ArrowRightLeft, ArrowUpRight, BarChart3, CalendarClock, Landmark, PiggyBank, Plus, ReceiptText, WalletCards } from "lucide-react";

import { archiveAccount, setBillActive, setIncomeActive, voidTransaction } from "@/features/finance/actions";
import { getFinanceAnalytics } from "@/features/finance/analytics-queries";
import { AccountForm, BillForm, CategoryForm, IncomeForm, RecurringAccountForm, TransactionForm, TransferForm } from "@/features/finance/finance-forms";
import { addMoney, formatMoney } from "@/features/finance/money";
import { getCashFlowForecast } from "@/features/finance/planning-queries";
import { getFinanceOverview } from "@/features/finance/queries";
import { getAuthenticatedAppContext } from "@/features/shared/server-context";

export const metadata: Metadata = { title: "Finance" };
export const dynamic = "force-dynamic";

const panel = "rounded-2xl border border-border bg-card p-5 shadow-sm sm:p-6";
const detail = "group rounded-xl border border-border bg-background open:bg-card";
const summary = "flex cursor-pointer list-none items-center justify-between gap-3 px-4 py-3 font-semibold marker:hidden";

function titleCase(value: string) {
  return value.replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase());
}

export default async function FinancePage({ searchParams }: { searchParams: Promise<{ error?: string; success?: string }> }) {
  const notice = await searchParams;
  const context = await getAuthenticatedAppContext();
  const [data, analytics, planning] = await Promise.all([getFinanceOverview(context), getFinanceAnalytics(undefined, context), getCashFlowForecast("30", undefined, context)]);
  const activeAccounts = data.accounts.filter((account) => !account.archivedAt);
  const totals = new Map<string, bigint>();
  for (const account of activeAccounts.filter((item) => item.includeInNetWorth)) {
    totals.set(account.currency, addMoney([totals.get(account.currency) ?? BigInt(0), account.currentBalance]));
  }
  const today = context.today; const defaultCurrency = context.profile.currency;
  const hasData = data.accounts.length > 0;

  return <div className="space-y-8">
    <header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between">
      <div><p className="text-sm font-semibold text-primary">Finance Core</p><h1 className="mt-1 text-3xl font-bold tracking-tight">Your financial ledger</h1><p className="mt-2 max-w-2xl text-sm text-muted-foreground">Exact balances from opening values and posted activity. No fabricated insights and no hidden balance overrides.</p></div>
      <nav className="flex max-w-full gap-1 overflow-x-auto rounded-xl border border-border bg-card p-1 text-sm" aria-label="Finance sections">
        <a className="rounded-lg px-3 py-2 hover:bg-muted" href="#accounts">Accounts</a><a className="rounded-lg px-3 py-2 hover:bg-muted" href="#transactions">Transactions</a><a className="rounded-lg px-3 py-2 hover:bg-muted" href="#recurring">Recurring</a><Link className="rounded-lg px-3 py-2 hover:bg-muted" href="/finance/budget">Budget</Link><Link className="rounded-lg px-3 py-2 hover:bg-muted" href="/finance/analytics">Analytics</Link><Link className="rounded-lg px-3 py-2 hover:bg-muted" href="/finance/planning">Planning</Link>
      </nav>
    </header>

    {notice.error ? <p role="alert" className="rounded-xl border border-destructive/30 bg-destructive/10 px-4 py-3 text-sm text-destructive">{notice.error}</p> : null}
    {notice.success ? <p role="status" className="rounded-xl border border-success/30 bg-success/10 px-4 py-3 text-sm text-success">{notice.success}</p> : null}

    {!hasData ? <section className={`${panel} overflow-hidden bg-gradient-to-br from-card to-accent/40`}>
      <div className="flex size-12 items-center justify-center rounded-xl bg-primary text-primary-foreground"><WalletCards /></div>
      <h2 className="mt-5 text-xl font-bold">Start with what you know</h2>
      <p className="mt-2 max-w-xl text-sm text-muted-foreground">Create an account for ledger balances, or add upcoming bills and paydays now and assign their accounts later.</p>
      <ol className="mt-5 grid gap-3 text-sm sm:grid-cols-2 lg:grid-cols-4"><li className="rounded-xl bg-background p-4"><b>1.</b> Add known schedules</li><li className="rounded-xl bg-background p-4"><b>2.</b> Create an account when ready</li><li className="rounded-xl bg-background p-4"><b>3.</b> Set its opening balance</li><li className="rounded-xl bg-background p-4"><b>4.</b> Record actual transactions</li></ol>
    </section> : null}

    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
      <article className={panel}><div className="flex items-center gap-2 text-sm text-muted-foreground"><Landmark className="size-4" /> Included balances</div><div className="mt-3 space-y-1">{totals.size ? [...totals].map(([currency, amount]) => <p className="text-2xl font-bold" key={currency}>{formatMoney(amount, currency)}</p>) : <p className="text-sm text-muted-foreground">No active included accounts yet.</p>}</div></article>
      <article className={panel}><div className="flex items-center gap-2 text-sm text-muted-foreground"><CalendarClock className="size-4" /> Next bill</div>{planning.nextBill ? <><p className="mt-3 font-bold">{planning.nextBill.name}</p><p className="text-sm text-muted-foreground">{formatMoney(-planning.nextBill.amount, planning.nextBill.currency)} · {planning.nextBill.date}{planning.nextBill.accountId ? "" : " · Unassigned"}</p></> : <p className="mt-3 text-sm text-muted-foreground">No bill in the next 30 days.</p>}</article>
      <article className={panel}><div className="flex items-center gap-2 text-sm text-muted-foreground"><ArrowDownLeft className="size-4" /> Next payday</div>{planning.nextPayday ? <><p className="mt-3 font-bold">{planning.nextPayday.name}</p><p className="text-sm text-muted-foreground">{formatMoney(planning.nextPayday.amount, planning.nextPayday.currency)} · {planning.nextPayday.date}{planning.nextPayday.accountId ? "" : " · Unassigned"}</p></> : <p className="mt-3 text-sm text-muted-foreground">No payday in the next 30 days.</p>}</article>
      <article className={panel}><div className="flex items-center gap-2 text-sm text-muted-foreground"><CalendarClock className="size-4" /> 30-day scheduled flow</div>{planning.totals.length ? <div className="mt-3 space-y-2">{planning.totals.map((item) => <div key={item.currency}><p className="font-bold">{item.currency}: {formatMoney(item.netScheduled, item.currency)} net</p><p className="text-xs text-muted-foreground">{formatMoney(item.income, item.currency)} in · {formatMoney(item.bills, item.currency)} out{item.unassignedBills > BigInt(0) ? ` · ${formatMoney(item.unassignedBills, item.currency)} unassigned` : ""}</p></div>)}</div> : <p className="mt-3 text-sm text-muted-foreground">No scheduled flow.</p>}<Link className="mt-3 inline-block text-xs font-semibold text-primary" href="/finance/planning">Open planning →</Link></article>
    </section>

    {analytics.current.byCurrency.length ? <section className="space-y-4"><div className="flex items-end justify-between gap-3"><div><h2 className="text-xl font-bold">This month</h2><p className="text-sm text-muted-foreground">Posted income and expenses, grouped by currency.</p></div><Link className="text-sm font-semibold text-primary" href="/finance/analytics">Full analytics →</Link></div><div className="grid gap-4 lg:grid-cols-2">{analytics.current.byCurrency.map((metrics) => { const budget = analytics.budgets.find((item) => item.row.currency === metrics.currency); return <article className={panel} key={metrics.currency}><div className="flex items-center justify-between"><p className="font-bold">{metrics.currency}</p><BarChart3 className="size-5 text-primary" /></div><div className="mt-4 grid grid-cols-3 gap-3 text-sm"><div><p className="text-muted-foreground">Income</p><p className="mt-1 font-bold text-financial-positive">{formatMoney(metrics.income, metrics.currency)}</p></div><div><p className="text-muted-foreground">Expenses</p><p className="mt-1 font-bold">{formatMoney(metrics.expenses, metrics.currency)}</p></div><div><p className="text-muted-foreground">Net cash flow</p><p className={`mt-1 font-bold ${metrics.netCashFlow < BigInt(0) ? "text-financial-negative" : "text-financial-positive"}`}>{formatMoney(metrics.netCashFlow, metrics.currency)}</p></div></div>{budget ? <div className="mt-4 border-t border-border pt-3"><div className="flex justify-between text-xs"><span>{budget.status.percentageUsed?.toFixed(1)}% of budget used</span><span>{formatMoney(budget.status.remaining, metrics.currency)} left</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-muted"><div className={budget.status.overAmount > BigInt(0) ? "h-full bg-destructive" : "h-full bg-primary"} style={{ width: `${Math.min(budget.status.percentageUsed ?? 0, 100)}%` }} /></div></div> : <Link className="mt-4 flex items-center gap-2 border-t border-border pt-3 text-xs font-semibold text-primary" href="/finance/budget"><PiggyBank className="size-4" /> Create a monthly budget</Link>}</article>; })}</div></section> : hasData ? <section className="rounded-xl border border-dashed border-border p-5"><p className="font-semibold">Ready for your first monthly insight</p><p className="mt-1 text-sm text-muted-foreground">Add a posted transaction, then income, spending, and budget performance will appear here.</p></section> : null}

    <section className="space-y-4" id="accounts"><div><h2 className="text-xl font-bold">Accounts</h2><p className="text-sm text-muted-foreground">Archived accounts keep their full history and derived balance.</p></div>
      <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{data.accounts.map((account) => <article className={`${panel} ${account.archivedAt ? "opacity-65" : ""}`} key={account.id}><div className="flex items-start justify-between gap-3"><div><h3 className="font-bold">{account.name}</h3><p className="text-xs text-muted-foreground">{titleCase(account.accountType)} · {account.currency}{account.archivedAt ? " · Archived" : ""}</p></div><WalletCards className="size-5 text-primary" /></div><p className={`mt-5 text-2xl font-bold ${account.currentBalance.startsWith("-") ? "text-financial-negative" : ""}`}>{formatMoney(account.currentBalance, account.currency)}</p><p className="mt-1 text-xs text-muted-foreground">Derived since {account.openingBalanceDate}</p>{!account.archivedAt ? <form action={archiveAccount} className="mt-4"><input type="hidden" name="id" value={account.id} /><button className="text-xs font-semibold text-muted-foreground hover:text-destructive">Archive account</button></form> : null}</article>)}</div>
      <details className={detail} open={!hasData}><summary className={summary}><span className="flex items-center gap-2"><Plus className="size-4" /> Add account</span><span className="text-muted-foreground group-open:rotate-45">+</span></summary><div className="border-t border-border p-4"><AccountForm defaultCurrency={defaultCurrency} today={today} /></div></details>
      <details className={detail}><summary className={summary}>Create a custom category <span className="text-muted-foreground group-open:rotate-45">+</span></summary><div className="border-t border-border p-4"><CategoryForm /></div></details>
    </section>

    <section className="space-y-4" id="transactions"><div><h2 className="text-xl font-bold">Transactions</h2><p className="text-sm text-muted-foreground">Expenses decrease an account, income increases it, and voided rows remain auditable.</p></div>
      {activeAccounts.length ? <div className="grid gap-3 lg:grid-cols-2"><details className={detail}><summary className={summary}><span className="flex items-center gap-2"><ReceiptText className="size-4" /> Add transaction</span><span>+</span></summary><div className="border-t border-border p-4"><TransactionForm accounts={data.accounts} categories={data.categories} today={today} /></div></details><details className={detail}><summary className={summary}><span className="flex items-center gap-2"><ArrowRightLeft className="size-4" /> Move between accounts</span><span>+</span></summary><div className="border-t border-border p-4"><TransferForm accounts={data.accounts} today={today} /></div></details></div> : <p className="rounded-xl border border-dashed border-border p-5 text-sm text-muted-foreground">Create an account before recording activity.</p>}
      <div className="overflow-hidden rounded-2xl border border-border bg-card"><div className="divide-y divide-border">{data.transactions.length ? data.transactions.map((transaction) => <article className={`flex items-center gap-3 p-4 ${transaction.status === "void" ? "opacity-50" : ""}`} key={transaction.id}><div className={`flex size-9 shrink-0 items-center justify-center rounded-full ${transaction.amount.startsWith("-") ? "bg-destructive/10 text-financial-negative" : "bg-success/10 text-financial-positive"}`}>{transaction.amount.startsWith("-") ? <ArrowUpRight className="size-4" /> : <ArrowDownLeft className="size-4" />}</div><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{transaction.merchant || transaction.description || titleCase(transaction.kind)}</p><p className="truncate text-xs text-muted-foreground">{transaction.accountName}{transaction.categoryName ? ` · ${transaction.categoryName}` : " · Transfer"} · {transaction.transaction_date}{transaction.status === "void" ? " · Voided" : ""}</p></div><p className={`text-sm font-bold ${transaction.amount.startsWith("-") ? "text-financial-negative" : "text-financial-positive"}`}>{formatMoney(transaction.amount, data.accounts.find((account) => account.id === transaction.account_id)?.currency ?? "CAD")}</p>{transaction.kind !== "transfer" && transaction.status !== "void" ? <div className="flex gap-2"><Link className="text-xs font-semibold text-primary" href={`/finance/transactions/${transaction.id}/edit`}>Edit</Link><form action={voidTransaction}><input type="hidden" name="id" value={transaction.id} /><button className="text-xs font-semibold text-destructive">Void</button></form></div> : null}</article>) : <p className="p-6 text-sm text-muted-foreground">No transactions yet. Your first posted entry will appear here.</p>}</div></div>
    </section>

    <section className="space-y-4" id="recurring"><div><h2 className="text-xl font-bold">Recurring schedule</h2><p className="text-sm text-muted-foreground">These are authoritative templates only; they do not create future ledger rows.</p></div>
      <div className="grid gap-3 lg:grid-cols-2"><details className={detail}><summary className={summary}>Add recurring bill <span>+</span></summary><div className="border-t border-border p-4"><BillForm accounts={data.accounts} categories={data.categories} defaultCurrency={defaultCurrency} today={today} /></div></details><details className={detail}><summary className={summary}>Add recurring income <span>+</span></summary><div className="border-t border-border p-4"><IncomeForm accounts={data.accounts} categories={data.categories} defaultCurrency={defaultCurrency} today={today} /></div></details></div>
      <div className="grid gap-4 lg:grid-cols-2"><div className={panel}><h3 className="font-bold">Bills</h3><div className="mt-3 divide-y divide-border">{data.bills.length ? data.bills.map((bill) => <div className="py-3" key={bill.id}><div className="flex items-center gap-3"><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{bill.name}</p><p className="text-xs text-muted-foreground">{bill.next_due_date} · {titleCase(bill.frequency)} · {bill.accountName}</p></div><p className="text-sm font-bold">{formatMoney(bill.expected_amount, bill.currency)}</p><form action={setBillActive}><input type="hidden" name="id" value={bill.id} /><input type="hidden" name="active" value={String(!bill.is_active)} /><button className="text-xs font-semibold text-primary">{bill.is_active ? "Pause" : "Resume"}</button></form></div><RecurringAccountForm accounts={data.accounts} currency={bill.currency} currentAccountId={bill.account_id} sourceId={bill.id} sourceType="bill" /></div>) : <p className="py-4 text-sm text-muted-foreground">No recurring bills.</p>}</div></div><div className={panel}><h3 className="font-bold">Income & paydays</h3><div className="mt-3 divide-y divide-border">{data.income.length ? data.income.map((item) => <div className="py-3" key={item.id}><div className="flex items-center gap-3"><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{item.name}</p><p className="text-xs text-muted-foreground">{item.next_payday} · {titleCase(item.frequency)} · {item.accountName}</p></div><p className="text-sm font-bold text-financial-positive">{formatMoney(item.expected_amount, item.currency)}</p><form action={setIncomeActive}><input type="hidden" name="id" value={item.id} /><input type="hidden" name="active" value={String(!item.is_active)} /><button className="text-xs font-semibold text-primary">{item.is_active ? "Pause" : "Resume"}</button></form></div><RecurringAccountForm accounts={data.accounts} currency={item.currency} currentAccountId={item.destination_account_id} sourceId={item.id} sourceType="income" /></div>) : <p className="py-4 text-sm text-muted-foreground">No recurring income.</p>}</div></div></div>
    </section>
  </div>;
}
