import type { Metadata } from "next";
import Link from "next/link";
import { Archive, CalendarDays, Check, Circle, ListChecks, RotateCcw, Target } from "lucide-react";

import { archiveGoal, archiveMilestone, setGoalStatus, setMilestoneCompletion } from "@/features/goals/actions";
import { GoalForm } from "@/features/goals/goal-form";
import { MilestoneForm } from "@/features/goals/milestone-form";
import { formatGoalCategory, formatGoalPercent, summarizeGoal } from "@/features/goals/progress";
import { getGoal } from "@/features/goals/queries";
import { cn } from "@/lib/utils";

export const metadata: Metadata = { title: "Goal" };

export default async function GoalPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ error?: string; success?: string }> }) {
  const [{ id }, query] = await Promise.all([params, searchParams]);
  const data = await getGoal(id);
  const goal = data.goal;
  const summary = summarizeGoal(goal);
  const milestones = goal.milestones.filter((milestone) => !milestone.archived_at);
  const tasks = goal.tasks.filter((task) => !task.archived_at);
  const percentage = summary.progress ? Number(formatGoalPercent(summary.progress.percent).replace("%", "")) : 0;
  const archived = Boolean(goal.archived_at);

  return <div className="space-y-7">
    <header><Link className="text-sm font-semibold text-primary" href="/goals">← All goals</Link><div className="mt-4 flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><div className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-secondary px-2.5 py-1 text-xs font-bold uppercase text-primary">{formatGoalCategory(goal.category)}</span><span className="rounded-full border px-2.5 py-1 text-xs font-semibold capitalize">{archived ? "Archived" : goal.status}</span></div><h1 className="mt-3 text-3xl font-bold sm:text-4xl">{goal.title}</h1>{goal.description ? <p className="mt-3 max-w-3xl text-sm leading-6 text-muted-foreground">{goal.description}</p> : null}</div>{!archived ? <Link className="rounded-lg bg-primary px-4 py-2 text-center text-sm font-semibold text-primary-foreground" href={`/tasks?goal=${goal.id}#new-task`}>Create related task</Link> : null}</div></header>
    {query.error ? <p className="rounded-lg bg-destructive/10 p-3 text-sm text-destructive">{query.error}</p> : null}{query.success ? <p className="rounded-lg bg-success/10 p-3 text-sm text-success">{query.success}</p> : null}

    <section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Info label="Deadline" value={goal.deadline ?? "No deadline"} /><Info label="Milestones" value={`${summary.milestonesCompleted} of ${summary.milestoneTotal}`} /><Info label="Related tasks" value={`${summary.tasksCompleted} of ${summary.taskTotal} complete`} /><Info label="Open tasks" value={String(summary.openTasks)} /></section>

    <section className="rounded-2xl border bg-card p-5 shadow-sm sm:p-6"><div className="flex items-center gap-2"><Target className="size-5 text-primary" /><h2 className="text-lg font-bold">Progress</h2></div>{summary.progressSummary ? <><p className="mt-4 text-xl font-bold text-primary">{summary.progressSummary}</p><div className="mt-3 h-3 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-primary" style={{ width: `${Math.min(100, percentage)}%` }} /></div>{summary.progress?.exceeded ? <p className="mt-2 text-sm font-semibold text-success">Goal exceeded. The actual value is preserved.</p> : null}</> : <p className="mt-4 text-sm text-muted-foreground">This goal has no measurable progress configured. Status and milestone progress remain available.</p>}</section>

    <section className="rounded-2xl border bg-card p-5 shadow-sm sm:p-6"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-lg font-bold">Milestones</h2><p className="text-sm text-muted-foreground">Lightweight checkpoints do not complete the goal automatically.</p></div></div><div className="mt-5 space-y-3">{milestones.length ? milestones.map((milestone) => <article className="rounded-xl border p-4" key={milestone.id}><div className="flex items-start gap-3"><span className={cn("mt-1 flex size-5 items-center justify-center rounded-full border", milestone.is_completed && "border-primary bg-primary text-primary-foreground")}>{milestone.is_completed ? <Check className="size-3" /> : <Circle className="size-3" />}</span><div className="min-w-0 flex-1"><h3 className={cn("font-semibold", milestone.is_completed && "text-muted-foreground line-through")}>{milestone.title}</h3>{milestone.target_date ? <p className="mt-1 flex items-center gap-1 text-xs text-muted-foreground"><CalendarDays className="size-3.5" />{milestone.target_date}</p> : null}{milestone.description ? <p className="mt-2 text-sm leading-6 text-muted-foreground">{milestone.description}</p> : null}</div></div>{!archived ? <div className="mt-3 flex flex-wrap gap-2"><form action={setMilestoneCompletion}><input name="id" type="hidden" value={milestone.id} /><input name="goalId" type="hidden" value={goal.id} /><input name="completed" type="hidden" value={String(!milestone.is_completed)} /><button className="inline-flex items-center gap-1 rounded-lg border px-3 py-2 text-xs font-semibold">{milestone.is_completed ? <RotateCcw className="size-3.5" /> : <Check className="size-3.5" />}{milestone.is_completed ? "Reopen" : "Complete"}</button></form><details className="rounded-lg border px-3 py-1.5"><summary className="cursor-pointer text-xs font-semibold">Edit</summary><div className="mt-3 min-w-[min(36rem,72vw)]"><MilestoneForm defaults={{ id: milestone.id, title: milestone.title, description: milestone.description, targetDate: milestone.target_date, sortOrder: milestone.sort_order }} goalId={goal.id} /></div></details><form action={archiveMilestone}><input name="id" type="hidden" value={milestone.id} /><input name="goalId" type="hidden" value={goal.id} /><button className="inline-flex items-center gap-1 px-3 py-2 text-xs font-semibold text-destructive"><Archive className="size-3.5" />Archive</button></form></div> : null}</article>) : <p className="rounded-xl border border-dashed p-5 text-sm text-muted-foreground">No milestones yet.</p>}</div>{!archived ? <details className="mt-5"><summary className="cursor-pointer text-sm font-semibold text-primary">Add milestone</summary><div className="mt-4"><MilestoneForm goalId={goal.id} /></div></details> : null}</section>

    <section className="rounded-2xl border bg-card p-5 shadow-sm sm:p-6"><div className="flex items-center justify-between gap-3"><div><h2 className="text-lg font-bold">Related tasks</h2><p className="text-sm text-muted-foreground">Task completion is informative and never completes this goal automatically.</p></div><ListChecks className="size-5 text-primary" /></div><div className="mt-5 space-y-2">{tasks.length ? tasks.map((task) => <Link className="flex items-center justify-between gap-3 rounded-xl border p-4 hover:border-primary/50" href={`/tasks?task=${task.id}#task-${task.id}`} key={task.id}><div><p className={cn("font-semibold", task.status === "completed" && "text-muted-foreground line-through")}>{task.title}</p><p className="mt-1 text-xs capitalize text-muted-foreground">{task.priority} priority · {task.status.replaceAll("_", " ")}</p></div><span className="text-xs font-semibold text-primary">View task</span></Link>) : <p className="rounded-xl border border-dashed p-5 text-sm text-muted-foreground">No Tasks are linked to this goal yet.</p>}</div></section>

    {!archived ? <section className="rounded-2xl border bg-card p-5 shadow-sm"><details><summary className="cursor-pointer text-lg font-bold">Edit goal</summary><div className="mt-4"><GoalForm defaults={{ id: goal.id, title: goal.title, description: goal.description, category: goal.category, status: goal.status, deadline: goal.deadline, progressMode: goal.progress_mode, currentValue: goal.current_value_decimal, targetValue: goal.target_value_decimal, unitLabel: goal.unit_label }} /></div></details><div className="mt-5 flex flex-wrap gap-2"><form action={setGoalStatus}><input name="id" type="hidden" value={goal.id} /><input name="status" type="hidden" value={goal.status === "completed" ? "active" : "completed"} /><button className="inline-flex items-center gap-1 rounded-lg border px-3 py-2 text-sm font-semibold">{goal.status === "completed" ? <RotateCcw className="size-4" /> : <Check className="size-4" />}{goal.status === "completed" ? "Reopen goal" : "Complete goal"}</button></form><form action={archiveGoal}><input name="id" type="hidden" value={goal.id} /><button className="inline-flex items-center gap-1 rounded-lg px-3 py-2 text-sm font-semibold text-destructive"><Archive className="size-4" />Archive goal</button></form></div></section> : <p className="rounded-xl border border-dashed p-5 text-sm text-muted-foreground">This goal is archived and retained as read-only history.</p>}
  </div>;
}

function Info({ label, value }: { label: string; value: string }) { return <div className="rounded-2xl border bg-card p-4"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 font-bold">{value}</p></div>; }
