import Link from "next/link";
import { FinanceTrendChart } from "@/features/analytics/analytics-charts";
import { AnalyticsRangeControls, AnalyticsSectionNav } from "@/features/analytics/range-controls";
import { getFinanceDeepAnalytics } from "@/features/analytics/deep-service";
import { formatMoney } from "@/features/finance/money";

export const metadata = { title: "Finance Analytics" };
const panel = "rounded-2xl border bg-card p-5 shadow-sm sm:p-6";
type Query = { range?: string | string[]; from?: string | string[]; to?: string | string[] };
function change(value: number | null) { return value === null ? "Not comparable (previous value was zero)" : `${value > 0 ? "+" : ""}${value.toFixed(1)}% vs previous period`; }
function monthLabel(month: string) { return new Intl.DateTimeFormat("en-CA", { month: "long", year: "numeric", timeZone: "UTC" }).format(new Date(`${month}-01T12:00:00Z`)); }

export default async function FinanceAnalyticsPage({ searchParams }: { searchParams: Promise<Query> }) {
  const data = await getFinanceDeepAnalytics(await searchParams); const currencies = data.comparisons.map((item) => item.currency);
  return <div className="space-y-7">
    <header><Link className="text-sm font-semibold text-primary" href="/analytics">← Analytics overview</Link><h1 className="mt-2 text-3xl font-bold tracking-tight">Finance analytics</h1><p className="mt-2 max-w-3xl text-sm text-muted-foreground">Posted ledger activity, exact currency-separated comparisons, and monthly budget performance.</p></header>
    <AnalyticsSectionNav active="finance"/><AnalyticsRangeControls basePath="/analytics/finance" range={data.range} selection={data.rangeSelection} timeZone={data.timeZone}/>
    <p className="text-xs text-muted-foreground">Previous comparison period: {data.previousRange.start} → {data.previousRange.end}, immediately preceding and equal in duration.</p>

    {currencies.length ? currencies.map((currency) => { const summary = data.comparisons.find((item) => item.currency === currency)!; return <section className={panel} key={currency}><h2 className="text-xl font-bold">Cash flow · {currency}</h2><div className="mt-4 grid gap-3 sm:grid-cols-3"><article className="rounded-xl border p-4"><p className="text-sm text-muted-foreground">Income</p><p className="mt-1 text-2xl font-bold">{formatMoney(summary.income, currency)}</p><p className="mt-1 text-xs text-muted-foreground">{change(summary.incomeChange)}</p></article><article className="rounded-xl border p-4"><p className="text-sm text-muted-foreground">Expenses</p><p className="mt-1 text-2xl font-bold">{formatMoney(summary.expenses, currency)}</p><p className="mt-1 text-xs text-muted-foreground">{change(summary.expenseChange)}</p></article><article className="rounded-xl border p-4"><p className="text-sm text-muted-foreground">Net cash flow</p><p className="mt-1 text-2xl font-bold">{formatMoney(summary.netCashFlow, currency)}</p><p className="mt-1 text-xs text-muted-foreground">Income minus expenses</p></article></div><div className="mt-4 rounded-xl border p-3"><h3 className="px-2 pt-1 font-semibold">Income and expenses over time</h3><FinanceTrendChart currency={currency} data={data.trend.filter((item) => item.currency === currency)}/></div></section>; }) : <section className="rounded-2xl border border-dashed p-8 text-center text-sm text-muted-foreground">No posted income or expense activity in this range.</section>}

    <section className={panel}><div className="flex items-center justify-between gap-3"><div><h2 className="text-xl font-bold">Where spending went</h2><p className="text-sm text-muted-foreground">Ranked independently within each currency.</p></div><Link className="text-sm font-semibold text-primary" href="/finance#transactions">View transactions</Link></div>{data.categories.length ? <div className="mt-4 overflow-x-auto"><table className="w-full min-w-[660px] text-left text-sm"><thead className="text-xs uppercase text-muted-foreground"><tr><th className="pb-2">Category</th><th>Currency</th><th>Amount</th><th>Share</th><th>Transactions</th><th>Change</th></tr></thead><tbody>{data.categories.map((item) => <tr className="border-t" key={`${item.currency}:${item.categoryId}`}><td className="py-3 font-semibold">{item.rank}. {item.categoryName}</td><td>{item.currency}</td><td>{formatMoney(item.amount, item.currency)}</td><td>{item.sharePercent?.toFixed(1) ?? "—"}%</td><td>{item.count}</td><td>{change(item.changePercent)}</td></tr>)}</tbody></table></div> : <p className="mt-5 rounded-xl border border-dashed p-6 text-center text-sm text-muted-foreground">No expense categories have activity in this range.</p>}</section>

    <section className={panel}><div className="flex items-center justify-between gap-3"><div><h2 className="text-xl font-bold">Monthly budget performance</h2><p className="text-sm text-muted-foreground">Budgets are never prorated. Each configured budget is compared with its complete calendar month.</p></div><Link className="text-sm font-semibold text-primary" href="/finance/budget">Manage budgets</Link></div>{data.budgets.length ? <div className="mt-4 space-y-4">{data.budgets.map((budget) => <article className="rounded-xl border p-4" key={budget.id}><div className="flex flex-wrap items-start justify-between gap-2"><div><h3 className="font-bold">{monthLabel(budget.month)} · {budget.currency}</h3><p className="text-xs text-muted-foreground">{budget.utilization?.toFixed(1) ?? "—"}% utilized</p></div><p className="font-semibold">{formatMoney(budget.actual, budget.currency)} of {formatMoney(budget.overallLimit, budget.currency)}</p></div><div className="mt-3 grid gap-2 text-sm sm:grid-cols-3"><p>Remaining: <strong>{formatMoney(budget.remaining, budget.currency)}</strong></p><p>Over: <strong>{formatMoney(budget.over, budget.currency)}</strong></p><p>Unbudgeted: <strong>{formatMoney(budget.unbudgeted, budget.currency)}</strong></p></div>{budget.categories.length ? <div className="mt-3 divide-y border-t">{budget.categories.map((category) => <div className="grid gap-1 py-2 text-sm sm:grid-cols-[1fr_auto_auto] sm:gap-4" key={category.categoryId}><span>{category.categoryName}</span><span>{formatMoney(category.actual, budget.currency)} / {formatMoney(category.limit, budget.currency)}</span><strong>{category.over !== "0.0000" ? `${formatMoney(category.over, budget.currency)} over` : `${formatMoney(category.remaining, budget.currency)} left`}</strong></div>)}</div> : null}</article>)}</div> : <p className="mt-5 rounded-xl border border-dashed p-6 text-center text-sm text-muted-foreground">No monthly budgets are configured for the calendar months touched by this range.</p>}</section>

    <section className="grid gap-6 lg:grid-cols-2"><div className={panel}><h2 className="text-xl font-bold">Most spending by merchant/payee</h2><p className="text-sm text-muted-foreground">Exact entered names only; no fuzzy normalization.</p>{data.merchants.length ? <ol className="mt-4 space-y-2">{data.merchants.slice(0, 10).map((item) => <li className="flex justify-between gap-3 rounded-lg border px-3 py-2 text-sm" key={`${item.currency}:${item.merchant}`}><span className="min-w-0 truncate">{item.merchant} <span className="text-muted-foreground">· {item.count}</span></span><strong>{formatMoney(item.amount, item.currency)}</strong></li>)}</ol> : <p className="mt-4 text-sm text-muted-foreground">Not enough merchant/payee data yet.</p>}</div><div className={panel}><h2 className="text-xl font-bold">Current net worth balances</h2><p className="text-sm text-muted-foreground">Current derived balances only—not historical snapshots.</p>{data.netWorth.length ? <div className="mt-4 space-y-2">{data.netWorth.map((item) => <p className="flex justify-between rounded-lg border px-3 py-2" key={item.currency}><span>{item.currency}</span><strong>{formatMoney(item.amount, item.currency)}</strong></p>)}</div> : <p className="mt-4 text-sm text-muted-foreground">No included active account balances.</p>}</div></section>
  </div>;
}
