import Link from "next/link";
import { ArrowDownRight, ArrowUpRight, CalendarDays, CircleDollarSign, Landmark, Repeat2 } from "lucide-react";

import { getFinanceAnalytics } from "@/features/finance/analytics-queries";
import { CategorySpendingChart, MonthComparisonChart } from "@/features/finance/finance-charts";
import { moneyToDecimal, formatMoney } from "@/features/finance/money";
import { nextMonthKey, previousMonthKey } from "@/features/finance/date-ranges";

export const metadata = { title: "Finance Analytics" };
export const dynamic = "force-dynamic";

const panel = "rounded-2xl border border-border bg-card p-5 shadow-sm sm:p-6";

function validMonth(value?: string) {
  return value && /^\d{4}-(0[1-9]|1[0-2])$/.test(value) ? value : undefined;
}

function monthLabel(month: string) {
  return new Intl.DateTimeFormat("en-CA", { month: "long", year: "numeric", timeZone: "UTC" }).format(new Date(`${month}-01T12:00:00Z`));
}

export default async function FinanceAnalyticsPage({ searchParams }: { searchParams: Promise<{ month?: string }> }) {
  const params = await searchParams;
  const data = await getFinanceAnalytics(validMonth(params.month));
  const hasActivity = data.current.byCurrency.length > 0;

  return <div className="space-y-8">
    <header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><Link className="text-sm font-semibold text-primary" href="/finance">← Finance overview</Link><h1 className="mt-2 text-3xl font-bold">Finance analytics</h1><p className="mt-2 max-w-2xl text-sm text-muted-foreground">Posted ledger activity for {monthLabel(data.month)}. Transfers, pending entries, and voided entries are excluded.</p></div><Link className="rounded-lg bg-primary px-4 py-2 text-sm font-semibold text-primary-foreground" href={`/finance/budget?month=${data.month}`}>Manage budget</Link></header>

    <nav className="flex items-center justify-between rounded-xl border border-border bg-card p-3"><Link className="rounded-lg px-3 py-2 text-sm font-semibold hover:bg-muted" href={`/finance/analytics?month=${previousMonthKey(data.month)}`}>← {monthLabel(data.previousMonth)}</Link><span className="text-sm font-bold">{monthLabel(data.month)}</span><Link className="rounded-lg px-3 py-2 text-sm font-semibold hover:bg-muted" href={`/finance/analytics?month=${nextMonthKey(data.month)}`}>{monthLabel(nextMonthKey(data.month))} →</Link></nav>

    {!hasActivity ? <section className="rounded-2xl border border-dashed border-border bg-card p-7"><CalendarDays className="size-9 text-primary" /><h2 className="mt-4 text-xl font-bold">No posted activity this month</h2><p className="mt-2 text-sm text-muted-foreground">Add an income or expense transaction to begin period analytics. Account balances and recurring obligations remain available below.</p><Link className="mt-4 inline-block text-sm font-semibold text-primary" href="/finance#transactions">Add a transaction →</Link></section> : null}

    {data.current.byCurrency.map((metrics) => <section className="space-y-4" key={metrics.currency}><div className="flex items-center gap-2"><CircleDollarSign className="size-5 text-primary" /><h2 className="text-xl font-bold">{metrics.currency} cash flow</h2></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><article className={panel}><p className="text-sm text-muted-foreground">Income</p><p className="mt-2 text-2xl font-bold text-financial-positive">{formatMoney(metrics.income, metrics.currency)}</p></article><article className={panel}><p className="text-sm text-muted-foreground">Expenses</p><p className="mt-2 text-2xl font-bold">{formatMoney(metrics.expenses, metrics.currency)}</p></article><article className={panel}><p className="text-sm text-muted-foreground">Net cash flow</p><p className={`mt-2 text-2xl font-bold ${metrics.netCashFlow < BigInt(0) ? "text-financial-negative" : "text-financial-positive"}`}>{formatMoney(metrics.netCashFlow, metrics.currency)}</p></article><article className={panel}><p className="text-sm text-muted-foreground">Net cash-flow rate</p><p className="mt-2 text-2xl font-bold">{metrics.savingsRate === null ? "—" : `${metrics.savingsRate.toFixed(1)}%`}</p><p className="text-xs text-muted-foreground">{metrics.savingsRate === null ? "Requires income" : `Average ${formatMoney(metrics.averageDailySpending, metrics.currency)}/day`}</p></article></div>
      <div className="grid gap-4 xl:grid-cols-2"><article className={panel}><h3 className="font-bold">Spending by category</h3><p className="text-sm text-muted-foreground">Where posted expenses went this month.</p><CategorySpendingChart currency={metrics.currency} data={data.current.byCategory.filter((item) => item.currency === metrics.currency && item.amount > BigInt(0)).slice(0, 8).map((item) => ({ name: item.categoryName, amount: Number(moneyToDecimal(item.amount)), color: item.color }))} /></article>{(() => { const comparison = data.comparisons.find((item) => item.currency === metrics.currency); const partial = data.today >= data.range.start && data.today <= data.range.end; return <article className={panel}><h3 className="font-bold">Month comparison</h3><p className="text-sm text-muted-foreground">{partial ? "This month is partial through today." : "Full calendar-month comparison."}</p><MonthComparisonChart currency={metrics.currency} currentLabel={monthLabel(data.month)} previousLabel={monthLabel(data.previousMonth)} data={[{ name: "Income", current: Number(moneyToDecimal(comparison?.currentIncome ?? BigInt(0))), previous: Number(moneyToDecimal(comparison?.previousIncome ?? BigInt(0))) }, { name: "Expenses", current: Number(moneyToDecimal(comparison?.currentExpenses ?? BigInt(0))), previous: Number(moneyToDecimal(comparison?.previousExpenses ?? BigInt(0))) }]} />{comparison ? <p className="text-sm text-muted-foreground">Expense change: {comparison.expenseChange === null ? "No comparable prior spending" : <span className={comparison.expenseChange > 0 ? "text-financial-negative" : "text-financial-positive"}>{comparison.expenseChange > 0 ? "+" : ""}{comparison.expenseChange.toFixed(1)}%</span>}</p> : null}</article>; })()}</div>
    </section>)}

    <section className="space-y-4"><div className="flex items-center justify-between gap-3"><div><h2 className="text-xl font-bold">Budget performance</h2><p className="text-sm text-muted-foreground">Actual spending remains derived from the ledger.</p></div><Link className="text-sm font-semibold text-primary" href={`/finance/budget?month=${data.month}`}>{data.budgets.length ? "Edit budgets" : "Create a budget"} →</Link></div>{data.budgets.length ? <div className="grid gap-4 lg:grid-cols-2">{data.budgets.map(({ row, status }) => <article className={panel} key={row.id}><div className="flex items-start justify-between gap-3"><div><h3 className="font-bold">{row.currency} monthly budget</h3><p className="text-sm text-muted-foreground">{status.percentageUsed?.toFixed(1)}% used · {data.daysRemaining} days remaining</p></div><p className={`font-bold ${status.remaining < BigInt(0) ? "text-financial-negative" : "text-financial-positive"}`}>{formatMoney(status.remaining, row.currency)} left</p></div><div className="mt-4 h-3 overflow-hidden rounded-full bg-muted"><div className={`h-full rounded-full ${status.overAmount > BigInt(0) ? "bg-destructive" : "bg-primary"}`} style={{ width: `${Math.min(status.percentageUsed ?? 0, 100)}%` }} /></div><div className="mt-3 flex justify-between text-sm"><span>{formatMoney(status.totalSpent, row.currency)} spent</span><span>{formatMoney(status.overallLimit, row.currency)} limit</span></div>{status.unbudgetedSpending > BigInt(0) ? <p className="mt-2 text-xs text-muted-foreground">Includes {formatMoney(status.unbudgetedSpending, row.currency)} in categories without limits.</p> : null}</article>)}</div> : <p className="rounded-xl border border-dashed border-border p-5 text-sm text-muted-foreground">No budget for this month. Spending analytics still include every posted expense.</p>}</section>

    <section className="grid gap-4 lg:grid-cols-2"><article className={panel}><div className="flex items-center gap-2"><Repeat2 className="size-5 text-primary" /><h2 className="text-lg font-bold">Recurring costs</h2></div>{data.recurringCosts.length ? <div className="mt-4 space-y-4">{data.recurringCosts.map((cost) => <div key={cost.currency}><p className="text-2xl font-bold">{formatMoney(cost.monthly, cost.currency)}<span className="text-sm font-normal text-muted-foreground"> / month</span></p><p className="text-sm text-muted-foreground">{formatMoney(cost.annual, cost.currency)} expected annually · {cost.currency}</p></div>)}</div> : <p className="mt-4 text-sm text-muted-foreground">No active recurring bills to normalize.</p>}</article><article className={panel}><div className="flex items-center gap-2"><Landmark className="size-5 text-primary" /><h2 className="text-lg font-bold">Net worth</h2></div>{data.netWorth.length ? <div className="mt-4 space-y-3">{data.netWorth.map((item) => <div className="flex items-center justify-between" key={item.currency}><span className="text-sm font-semibold">{item.currency}</span><span className={`text-2xl font-bold ${item.amount < BigInt(0) ? "text-financial-negative" : ""}`}>{formatMoney(item.amount, item.currency)}</span></div>)}</div> : <p className="mt-4 text-sm text-muted-foreground">No active accounts included in net worth.</p>}<p className="mt-3 text-xs text-muted-foreground">Credit-card debt reduces net worth. Archived and opted-out accounts are excluded.</p></article></section>

    <section><h2 className="text-xl font-bold">Largest expenses</h2>{data.current.largestExpenses.length ? <div className="mt-3 divide-y divide-border overflow-hidden rounded-2xl border border-border bg-card">{data.current.largestExpenses.map((transaction) => <div className="flex items-center gap-3 p-4" key={transaction.id}><span className="flex size-9 items-center justify-center rounded-full bg-destructive/10 text-destructive">{transaction.expenseAmount > BigInt(0) ? <ArrowUpRight className="size-4" /> : <ArrowDownRight className="size-4" />}</span><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{transaction.label}</p><p className="text-xs text-muted-foreground">{transaction.date}</p></div><p className="font-bold">{formatMoney(transaction.expenseAmount, transaction.currency)}</p></div>)}</div> : <p className="mt-3 rounded-xl border border-dashed border-border p-5 text-sm text-muted-foreground">No expenses in this period.</p>}</section>
  </div>;
}
