import Link from "next/link";
import { AlertTriangle, ArrowDown, ArrowUp, CalendarRange, Landmark, Link2Off } from "lucide-react";

import { ProjectedBalanceChart } from "@/features/finance/finance-charts";
import { addCalendarDays } from "@/features/finance/date-ranges";
import { formatMoney, moneyToDecimal } from "@/features/finance/money";
import { getCashFlowForecast } from "@/features/finance/planning-queries";

export const metadata = { title: "Cash-flow Planning" };
export const dynamic = "force-dynamic";

const panel = "rounded-2xl border border-border bg-card p-5 shadow-sm sm:p-6";
const horizons = [{ value: "7", label: "7 days" }, { value: "30", label: "30 days" }, { value: "60", label: "60 days" }, { value: "90", label: "90 days" }, { value: "month", label: "Month end" }];

export default async function PlanningPage({ searchParams }: { searchParams: Promise<{ horizon?: string; through?: string }> }) {
  const params = await searchParams;
  const forecast = await getCashFlowForecast(params.horizon, params.through);
  const accountNames = new Map(forecast.accountForecasts.map((item) => [item.account.id, item.account.name]));

  return <div className="space-y-8">
    <header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><Link className="text-sm font-semibold text-primary" href="/finance">← Finance overview</Link><h1 className="mt-2 text-3xl font-bold">Cash-flow planning</h1><p className="mt-2 max-w-2xl text-sm text-muted-foreground">An explainable projection of known recurring schedules from {forecast.range.start} through {forecast.range.end}. This is not a bank-posting guarantee or machine-learning prediction.</p></div><Link className="rounded-lg border border-border bg-card px-4 py-2 text-sm font-semibold" href="/finance/analytics">Historical analytics</Link></header>

    <section className="flex flex-wrap gap-2 rounded-xl border border-border bg-card p-3" aria-label="Forecast horizon">{horizons.map((item) => <Link className={`rounded-lg px-3 py-2 text-sm font-semibold ${forecast.horizon === item.value ? "bg-primary text-primary-foreground" : "hover:bg-muted"}`} href={`/finance/planning?horizon=${item.value}`} key={item.value}>{item.label}</Link>)}<form className="flex gap-2" method="get"><input type="hidden" name="horizon" value="custom" /><input aria-label="Custom forecast end date" className="h-9 rounded-lg border border-input bg-card px-2 text-sm" min={forecast.today} max={addCalendarDays(forecast.today, 366)} name="through" type="date" defaultValue={params.through} /><button className="rounded-lg border border-border px-3 text-sm font-semibold">Through date</button></form></section>

    <section className="grid gap-4 lg:grid-cols-2">{forecast.totals.length ? forecast.totals.map((total) => <article className={panel} key={total.currency}><div className="flex items-center justify-between"><h2 className="font-bold">{total.currency} scheduled flow</h2><CalendarRange className="size-5 text-primary" /></div><div className="mt-4 grid grid-cols-3 gap-3 text-sm"><div><p className="text-muted-foreground">Income</p><p className="mt-1 font-bold text-financial-positive">{formatMoney(total.income, total.currency)}</p></div><div><p className="text-muted-foreground">Bills</p><p className="mt-1 font-bold">{formatMoney(total.bills, total.currency)}</p></div><div><p className="text-muted-foreground">Net scheduled</p><p className={`mt-1 font-bold ${total.netScheduled < BigInt(0) ? "text-financial-negative" : "text-financial-positive"}`}>{formatMoney(total.netScheduled, total.currency)}</p></div></div>{total.unassignedBills > BigInt(0) || total.unassignedIncome > BigInt(0) ? <div className="mt-4 rounded-xl bg-warning/10 p-3 text-sm"><p className="flex items-center gap-2 font-semibold text-warning"><Link2Off className="size-4" /> Account assignment needed</p>{total.unassignedBills > BigInt(0) ? <p className="mt-1">{formatMoney(total.unassignedBills, total.currency)} in bills is unassigned.</p> : null}{total.unassignedIncome > BigInt(0) ? <p>{formatMoney(total.unassignedIncome, total.currency)} in income is unassigned.</p> : null}<Link className="mt-2 inline-block text-xs font-semibold text-primary" href="/finance#recurring">Assign accounts →</Link></div> : null}</article>) : <article className={`${panel} lg:col-span-2`}><h2 className="font-bold">No scheduled cash flow in this horizon</h2><p className="mt-2 text-sm text-muted-foreground">Add an active recurring bill or payday. An account is optional until an actual transaction is recorded.</p><Link className="mt-3 inline-block text-sm font-semibold text-primary" href="/finance#recurring">Add a schedule →</Link></article>}</section>

    <section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><article className={panel}><p className="text-sm text-muted-foreground">Next bill</p>{forecast.nextBill ? <><p className="mt-2 font-bold">{forecast.nextBill.name}</p><p className="text-sm">{forecast.nextBill.date} · {formatMoney(-forecast.nextBill.amount, forecast.nextBill.currency)}</p></> : <p className="mt-2 text-sm text-muted-foreground">None in range</p>}</article><article className={panel}><p className="text-sm text-muted-foreground">Next payday</p>{forecast.nextPayday ? <><p className="mt-2 font-bold">{forecast.nextPayday.name}</p><p className="text-sm">{forecast.nextPayday.date} · {formatMoney(forecast.nextPayday.amount, forecast.nextPayday.currency)}</p></> : <p className="mt-2 text-sm text-muted-foreground">None in range</p>}</article>{forecast.liquidity.map((item) => <article className={panel} key={item.currency}><p className="text-sm text-muted-foreground">Known liquid position · {item.currency}</p><p className="mt-2 text-2xl font-bold">{formatMoney(item.projected, item.currency)}</p><p className="text-xs text-muted-foreground">From {formatMoney(item.current, item.currency)} today</p></article>)}</section>

    {forecast.warnings.length ? <section className="rounded-2xl border border-warning/40 bg-warning/10 p-5"><h2 className="flex items-center gap-2 font-bold text-warning"><AlertTriangle className="size-5" /> Potential known-schedule shortfalls</h2><div className="mt-3 space-y-2">{forecast.warnings.map((warning) => <p className="text-sm" key={warning.accountId}>{warning.accountName} may fall below $0 on {warning.date} after {warning.after}: {formatMoney(warning.balance, warning.currency)}.</p>)}</div><p className="mt-3 text-xs text-muted-foreground">This only reflects assigned schedules and does not guarantee an overdraft or complete cash picture.</p></section> : null}

    <section><h2 className="text-xl font-bold">Known cash-flow timeline</h2><p className="mt-1 text-sm text-muted-foreground">Bills sort before income on the same date as a conservative display convention.</p>{forecast.timeline.length ? <div className="mt-4 divide-y divide-border overflow-hidden rounded-2xl border border-border bg-card">{forecast.timeline.map((entry) => <article className="flex items-center gap-3 p-4" key={entry.occurrenceId}><span className={`flex size-9 shrink-0 items-center justify-center rounded-full ${entry.type === "bill" ? "bg-destructive/10 text-destructive" : "bg-success/10 text-success"}`}>{entry.type === "bill" ? <ArrowDown className="size-4" /> : <ArrowUp className="size-4" />}</span><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{entry.name}</p><p className="text-xs text-muted-foreground">{entry.date} · {entry.accountId ? accountNames.get(entry.accountId) ?? "Archived account" : "Unassigned"}</p></div><p className={`font-bold ${entry.type === "bill" ? "text-financial-negative" : "text-financial-positive"}`}>{entry.type === "bill" ? "-" : "+"}{formatMoney(entry.type === "bill" ? -entry.amount : entry.amount, entry.currency)}</p></article>)}</div> : <p className="mt-4 rounded-xl border border-dashed border-border p-5 text-sm text-muted-foreground">No occurrences in this range.</p>}</section>

    <section><div className="flex items-end justify-between"><div><h2 className="text-xl font-bold">Account projections</h2><p className="text-sm text-muted-foreground">Only schedules assigned to each account affect its path.</p></div></div><div className="mt-4 grid gap-4 xl:grid-cols-2">{forecast.accountForecasts.filter((item) => !item.account.archivedAt).map((item) => <article className={panel} key={item.account.id}><div className="flex items-center justify-between gap-3"><div><h3 className="font-bold">{item.account.name}</h3><p className="text-xs text-muted-foreground">{item.account.accountType.replaceAll("_", " ")} · {item.account.currency}</p></div><Landmark className="size-5 text-primary" /></div><div className="mt-3 flex justify-between text-sm"><span>Today: <b>{formatMoney(item.startingBalance, item.account.currency)}</b></span><span>Known ending: <b>{formatMoney(item.endingBalance, item.account.currency)}</b></span></div><ProjectedBalanceChart accountName={item.account.name} currency={item.account.currency} data={item.points.map((point) => ({ date: point.date, label: point.label, balance: Number(moneyToDecimal(point.balance)) }))} /></article>)}</div></section>

    <section className="rounded-xl border border-border bg-muted/40 p-4 text-sm text-muted-foreground"><b className="text-foreground">Known scheduled only.</b> Discretionary-spending estimates are deferred because matching recurring bills to ordinary historical transactions is not reliable enough yet to prevent double-counting. Linked posted occurrences are suppressed from the projection; the mark-paid workflow remains deferred.</section>
  </div>;
}
