import type { Metadata } from "next";
import Link from "next/link";
import { ArrowLeft, CalendarRange, Clock3, GraduationCap } from "lucide-react";

import { CalendarItemCard } from "@/features/calendar/calendar-item-card";
import { getSchoolCalendarItems } from "@/features/school/calendar-provider";
import { formatPercent } from "@/features/school/grades";
import { assessmentLocalDate, daysUntilLabel, summarizeWorkload } from "@/features/school/planning";
import { getSchoolPlanning } from "@/features/school/queries";
import { getAuthenticatedAppContext } from "@/features/shared/server-context";

export const metadata: Metadata = { title: "School Planning" };
const panel = "rounded-2xl border bg-card p-5 shadow-sm";

export default async function SchoolPlanningPage({ searchParams }: { searchParams: Promise<{ term?: string; range?: string }> }) {
  const query = await searchParams;
  const context = await getAuthenticatedAppContext();
  const data = await getSchoolPlanning(query.term, context);
  const rangeKey = ["7", "14", "30", "term"].includes(query.range ?? "") ? query.range! : "14";
  const selectedRange = rangeKey === "7" ? data.ranges.seven : rangeKey === "30" ? data.ranges.thirty : rangeKey === "term" ? data.ranges.term : data.ranges.fourteen;
  const upcoming = data.upcoming.filter((assessment) => assessmentLocalDate(assessment, data.timezone) <= selectedRange.end);
  const summary = summarizeWorkload(upcoming);
  const courseMap = new Map(data.courses.map((course) => [course.id, course]));
  const schoolWeek = data.term ? (await getSchoolCalendarItems(data.ranges.seven, context)).filter((item) => data.courses.some((course) => item.sourceUrl.includes(course.id))) : [];

  return <div className="space-y-7">
    <header className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><Link className="inline-flex items-center gap-2 text-sm font-semibold text-primary" href="/school"><ArrowLeft className="size-4" />School</Link><h1 className="mt-3 text-3xl font-bold">Academic planning</h1><p className="mt-1 text-sm text-muted-foreground">Transparent workload and deadline concentration from your School records.</p></div><Link className="rounded-lg border bg-card px-4 py-2 text-sm font-semibold" href="/school/archive">School archive</Link></header>

    {data.terms.length ? <nav aria-label="Term selection" className="flex gap-2 overflow-x-auto pb-1">{data.terms.map((term) => <Link className={`whitespace-nowrap rounded-full px-4 py-2 text-sm font-semibold ${term.id === data.term?.id ? "bg-primary text-primary-foreground" : "border bg-card"}`} href={`/school/planning?term=${term.id}&range=${rangeKey}`} key={term.id}>{term.name}</Link>)}</nav> : null}

    {data.term ? <section className={panel}><div className="flex items-center gap-3"><GraduationCap className="size-6 text-primary" /><div><h2 className="text-xl font-bold">{data.term.name}</h2><p className="text-sm text-muted-foreground">{data.term.start_date} – {data.term.end_date}</p></div></div><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><div><p className="text-xs text-muted-foreground">Term elapsed</p><b className="text-2xl">{data.termProgress?.percentElapsed}%</b></div><div><p className="text-xs text-muted-foreground">Days remaining</p><b className="text-2xl">{data.termProgress?.remainingDays}</b></div><div><p className="text-xs text-muted-foreground">Courses</p><b className="text-2xl">{data.courses.length}</b></div><div><p className="text-xs text-muted-foreground">Assessments</p><b className="text-2xl">{data.assessmentProgress.completed} handled · {data.assessmentProgress.remaining} upcoming</b></div></div></section> : <div className={panel}>Create an academic term to begin planning.</div>}

    <section className={panel}><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-lg font-bold">Upcoming workload</h2><p className="text-sm text-muted-foreground">Combined weight is a concentration metric, not a difficulty score.</p></div><div className="flex gap-1">{[["7", "7 days"], ["14", "14 days"], ["30", "30 days"], ["term", "Rest of term"]].map(([value, label]) => <Link className={`rounded-lg px-3 py-2 text-xs font-semibold ${rangeKey === value ? "bg-primary text-primary-foreground" : "bg-muted"}`} href={`/school/planning?${data.term ? `term=${data.term.id}&` : ""}range=${value}`} key={value}>{label}</Link>)}</div></div><div className="mt-5 grid gap-3 sm:grid-cols-3"><div><p className="text-xs text-muted-foreground">Assessments</p><b className="text-2xl">{summary.assessmentCount}</b></div><div><p className="text-xs text-muted-foreground">Combined course weight</p><b className="text-2xl">{formatPercent(summary.combinedWeight)}</b></div><div><p className="text-xs text-muted-foreground">Entered effort estimates</p><b className="text-2xl">{summary.estimatedCount ? `${Math.round(summary.estimatedMinutes / 6) / 10}h` : "—"}</b><p className="text-xs text-muted-foreground">across {summary.estimatedCount} of {summary.assessmentCount}</p></div></div><div className="mt-5 space-y-3">{upcoming.length ? upcoming.map((assessment) => { const course = courseMap.get(assessment.course_id); const date = assessmentLocalDate(assessment, data.timezone); return <Link className="block rounded-xl border p-4 transition-colors hover:bg-muted/40" href={`/school/courses/${assessment.course_id}#assessment-${assessment.id}`} key={assessment.id}><div className="flex gap-3"><div className="flex-1"><p className="text-xs font-bold text-primary">{course?.code} · {date}</p><p className="font-semibold">{assessment.name}</p><p className="text-xs capitalize text-muted-foreground">{assessment.assessment_type.replaceAll("_", " ")} · {assessment.weight_percent}%{assessment.estimated_effort_minutes ? ` · ${Math.round(assessment.estimated_effort_minutes / 6) / 10}h estimated` : ""}</p></div><span className="text-xs font-semibold text-muted-foreground">{daysUntilLabel(data.today, date, assessment.assessment_type.includes("exam") || assessment.assessment_type === "midterm" ? "Exam" : "Due")}</span></div></Link>; }) : <p className="rounded-xl border border-dashed p-6 text-center text-sm text-muted-foreground">No upcoming assessments in this range.</p>}</div></section>

    <section className="grid gap-4 lg:grid-cols-2"><div className={panel}><div className="flex items-center gap-2"><CalendarRange className="size-5 text-primary" /><h2 className="text-lg font-bold">This academic week</h2></div><p className="mt-1 text-sm text-muted-foreground">{data.workload.assessmentCount} assessments · {formatPercent(data.workload.combinedWeight)} combined course weight</p><div className="mt-4 space-y-2">{schoolWeek.length ? schoolWeek.slice(0, 10).map((item) => <CalendarItemCard item={item} key={item.id} timeZone={data.timezone} />) : <p className="text-sm text-muted-foreground">No meetings or assessments this week.</p>}</div></div><div className={panel}><div className="flex items-center gap-2"><Clock3 className="size-5 text-primary" /><h2 className="text-lg font-bold">Exams & major assessments</h2></div><p className="mt-1 text-sm text-muted-foreground">Midterms, finals, projects, and presentations.</p><div className="mt-4 space-y-3">{data.major.length ? data.major.map((assessment) => { const course = courseMap.get(assessment.course_id); const date = assessmentLocalDate(assessment, data.timezone); return <Link className="block rounded-lg border p-3" href={`/school/courses/${assessment.course_id}#assessment-${assessment.id}`} key={assessment.id}><p className="text-xs font-bold text-primary">{course?.code} · {date}</p><p className="font-semibold">{assessment.name}</p><p className="text-xs text-muted-foreground">{assessment.weight_percent}% · {daysUntilLabel(data.today, date, "Due")}{assessment.location ? ` · ${assessment.location}` : ""}</p></Link>; }) : <p className="text-sm text-muted-foreground">No upcoming major assessments.</p>}</div></div></section>
  </div>;
}
