import "server-only";

import type { FunctionTool } from "openai/resources/responses/responses";

const object = (properties: Record<string, unknown>, required: string[] = []) => ({ type: "object", properties, required, additionalProperties: false });
const nullable = (type: string) => ({ type: [type, "null"] });
const nullableId = { type: ["string", "null"], format: "uuid" };

export const assistantMutationToolDefinitions: FunctionTool[] = [
  { type: "function", name: "create_task", description: "PROPOSAL ONLY. Prepare one Task for explicit user confirmation. This never writes immediately.", strict: true, parameters: object({ title: { type: "string" }, description: nullable("string"), priority: { type: ["string", "null"], enum: ["low", "medium", "high", "urgent", null] }, dueDate: nullable("string"), dueLocal: nullable("string"), estimatedEffortMinutes: nullable("number"), assessmentId: nullableId, goalId: nullableId }, ["title", "description", "priority", "dueDate", "dueLocal", "estimatedEffortMinutes", "assessmentId", "goalId"]) },
  { type: "function", name: "update_task", description: "PROPOSAL ONLY. Prepare changes to exactly one Task ID returned by a read tool. Omit unchanged fields. This never writes immediately.", strict: false, parameters: object({ taskId: { type: "string", format: "uuid" }, title: { type: "string" }, description: { type: ["string", "null"] }, priority: { type: "string", enum: ["low", "medium", "high", "urgent"] }, dueKind: { type: "string", enum: ["none", "date", "timed"] }, dueDate: { type: "string" }, dueLocal: { type: "string" }, estimatedEffortMinutes: { type: ["integer", "null"] }, assessmentId: nullableId, goalId: nullableId }, ["taskId"]) },
  { type: "function", name: "set_task_status", description: "PROPOSAL ONLY. Prepare a Todo, In progress, Completed, or reopen-to-Todo transition for exactly one owned Task. This never writes immediately.", strict: true, parameters: object({ taskId: { type: "string", format: "uuid" }, status: { type: "string", enum: ["todo", "in_progress", "completed"] } }, ["taskId", "status"]) },
  { type: "function", name: "create_calendar_event", description: "PROPOSAL ONLY. Prepare one non-recurring native Calendar event for confirmation. Timed events require explicit local start and end; all-day events require inclusive start and end dates.", strict: true, parameters: object({ title: { type: "string" }, eventType: nullable("string"), description: nullable("string"), location: nullable("string"), allDay: { type: "boolean" }, startDate: nullable("string"), endDate: nullable("string"), startsAtLocal: nullable("string"), endsAtLocal: nullable("string") }, ["title", "eventType", "description", "location", "allDay", "startDate", "endDate", "startsAtLocal", "endsAtLocal"]) },
  { type: "function", name: "update_calendar_event", description: "PROPOSAL ONLY. Prepare changes to exactly one owned, native, non-recurring Calendar event ID returned by a read tool. Omit unchanged fields. Never edit projected items.", strict: false, parameters: object({ eventId: { type: "string", format: "uuid" }, title: { type: "string" }, eventType: { type: ["string", "null"] }, description: { type: ["string", "null"] }, location: { type: ["string", "null"] }, allDay: { type: "boolean" }, startDate: { type: ["string", "null"] }, endDate: { type: ["string", "null"] }, startsAtLocal: { type: ["string", "null"] }, endsAtLocal: { type: ["string", "null"] } }, ["eventId"]) },
  { type: "function", name: "create_goal", description: "PROPOSAL ONLY. Prepare one Goal for explicit confirmation. Exact progress values are decimal strings. This never writes immediately.", strict: true, parameters: object({ title: { type: "string" }, description: nullable("string"), category: { type: "string", enum: ["finance", "school", "career", "personal", "health_fitness", "project", "other"] }, deadline: nullable("string"), progressMode: { type: "string", enum: ["none", "percentage", "numeric"] }, currentValue: nullable("string"), targetValue: nullable("string"), unitLabel: nullable("string") }, ["title", "description", "category", "deadline", "progressMode", "currentValue", "targetValue", "unitLabel"]) },
  { type: "function", name: "update_goal", description: "PROPOSAL ONLY. Prepare supported field changes to exactly one owned active Goal ID returned by a read tool. Omit unchanged fields. This never writes immediately.", strict: false, parameters: object({ goalId: { type: "string", format: "uuid" }, title: { type: "string" }, description: { type: ["string", "null"] }, category: { type: "string", enum: ["finance", "school", "career", "personal", "health_fitness", "project", "other"] }, deadline: { type: ["string", "null"] }, progressMode: { type: "string", enum: ["none", "percentage", "numeric"] }, currentValue: { type: ["string", "null"] }, targetValue: { type: ["string", "null"] }, unitLabel: { type: ["string", "null"] } }, ["goalId"]) },
  { type: "function", name: "set_goal_status", description: "PROPOSAL ONLY. Prepare completion or reopening for exactly one owned active Goal. This never writes immediately.", strict: true, parameters: object({ goalId: { type: "string", format: "uuid" }, status: { type: "string", enum: ["active", "completed"] } }, ["goalId", "status"]) },
  { type: "function", name: "update_goal_progress", description: "PROPOSAL ONLY. Prepare an exact current-value update for one measured Goal. Reaching the target does not complete it. This never writes immediately.", strict: true, parameters: object({ goalId: { type: "string", format: "uuid" }, currentValue: { type: "string" } }, ["goalId", "currentValue"]) },
  { type: "function", name: "update_assessment", description: "PROPOSAL ONLY. Prepare supported metadata or timing changes to one exact owned assessment. Weight, course, score, status, archive, and creation are excluded.", strict: false, parameters: object({ assessmentId: { type: "string", format: "uuid" }, title: { type: "string" }, assessmentType: { type: "string", enum: ["assignment", "quiz", "midterm", "final_exam", "project", "lab", "participation", "presentation", "other"] }, timingType: { type: "string", enum: ["deadline", "scheduled", "all_day"] }, dueLocal: { type: "string" }, startsLocal: { type: "string" }, endsLocal: { type: "string" }, eventDate: { type: "string" }, estimatedEffortMinutes: { type: ["integer", "null"] }, location: { type: ["string", "null"] }, notes: { type: ["string", "null"] } }, ["assessmentId"]) },
  { type: "function", name: "set_assessment_score", description: "PROPOSAL ONLY. Prepare one actual assessment score for confirmation. Use raw earned/maximum or an explicit percentage; never use for hypotheticals.", strict: true, parameters: object({ assessmentId: { type: "string", format: "uuid" }, mode: { type: "string", enum: ["raw", "percentage"] }, earned: nullable("string"), maximum: nullable("string"), percentage: nullable("string") }, ["assessmentId", "mode", "earned", "maximum", "percentage"]) },
  { type: "function", name: "clear_assessment_score", description: "PROPOSAL ONLY. Prepare removal of one recorded assessment score. A graded assessment returns to Upcoming.", strict: true, parameters: object({ assessmentId: { type: "string", format: "uuid" } }, ["assessmentId"]) },
  { type: "function", name: "set_assessment_status", description: "PROPOSAL ONLY. Prepare Upcoming, Submitted, Missed, or Exempt status for one assessment. Missed counts as zero; Exempt is excluded.", strict: true, parameters: object({ assessmentId: { type: "string", format: "uuid" }, status: { type: "string", enum: ["upcoming", "submitted", "missed", "exempt"] } }, ["assessmentId", "status"]) },
];

export const assistantMutationToolNames = new Set(assistantMutationToolDefinitions.map((tool) => tool.name));
