import type { Metadata } from "next";
import Link from "next/link";
import { Archive, BarChart3, BookOpen, CalendarDays, GraduationCap, Plus } from "lucide-react";

import { archiveSchoolEntity, saveCourse, saveTerm } from "@/features/school/actions";
import { formatPercent } from "@/features/school/grades";
import { assessmentLocalDate, daysUntilLabel } from "@/features/school/planning";
import { getSchoolPlanning } from "@/features/school/queries";

export const metadata: Metadata = { title: "School" };
const input = "mt-1 h-10 w-full rounded-lg border bg-card px-3 text-sm";
const panel = "rounded-2xl border bg-card p-5 shadow-sm";

export default async function SchoolPage({ searchParams }: { searchParams: Promise<{ error?: string; success?: string; term?: string }> }) {
  const query = await searchParams;
  const data = await getSchoolPlanning(query.term);
  const courseMap = new Map(data.courses.map((course) => [course.id, course]));

  return <div className="space-y-8">
    {query.error ? <p className="rounded-lg bg-destructive/10 p-3 text-sm text-destructive">{query.error}</p> : null}{query.success ? <p className="rounded-lg bg-success/10 p-3 text-sm text-success">{query.success}</p> : null}
    <header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-semibold text-primary">Academic command centre</p><h1 className="mt-1 text-3xl font-bold sm:text-4xl">School</h1><p className="mt-2 text-sm text-muted-foreground">Semester standing, upcoming workload, resources, and deterministic grade planning.</p></div><div className="flex gap-2"><Link className="inline-flex items-center gap-2 rounded-lg bg-primary px-4 py-2 text-sm font-semibold text-primary-foreground" href={`/school/planning${data.term ? `?term=${data.term.id}` : ""}`}><BarChart3 className="size-4" />Planning</Link><Link className="inline-flex items-center gap-2 rounded-lg border bg-card px-4 py-2 text-sm font-semibold" href="/school/archive"><Archive className="size-4" />Archive</Link></div></header>

    {data.terms.length ? <nav aria-label="Academic terms" className="flex gap-2 overflow-x-auto pb-1">{data.terms.map((term) => <Link className={`whitespace-nowrap rounded-full px-4 py-2 text-sm font-semibold ${term.id === data.term?.id ? "bg-primary text-primary-foreground" : "border bg-card"}`} href={`/school?term=${term.id}`} key={term.id}>{term.name}</Link>)}</nav> : null}

    <section className="grid gap-4 lg:grid-cols-[1fr_22rem]"><div className={panel}><div className="flex gap-3"><GraduationCap className="size-6 text-primary" /><div><h2 className="text-xl font-bold">{data.term?.name ?? "No academic term"}</h2><p className="text-sm text-muted-foreground">{data.term ? `${data.term.start_date} – ${data.term.end_date}` : "Add a semester to begin."}</p></div></div>{data.termProgress ? <div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-4"><div><p className="text-xs text-muted-foreground">Elapsed</p><b>{data.termProgress.percentElapsed}%</b></div><div><p className="text-xs text-muted-foreground">Days left</p><b>{data.termProgress.remainingDays}</b></div><div><p className="text-xs text-muted-foreground">Handled</p><b>{data.assessmentProgress.completed}</b></div><div><p className="text-xs text-muted-foreground">Upcoming</p><b>{data.assessmentProgress.remaining}</b></div></div> : null}<div className="mt-5 grid gap-3 sm:grid-cols-2">{data.courses.length ? data.courses.map((course) => { const next = data.upcoming.find((assessment) => assessment.course_id === course.id); return <Link className="rounded-xl border p-4 hover:border-primary" href={`/school/courses/${course.id}`} key={course.id}><p className="font-bold">{course.code}</p><p className="text-sm text-muted-foreground">{course.name}</p><div className="mt-3 flex flex-wrap gap-x-4 gap-y-1 text-sm"><span><b>{formatPercent(course.grade.completedWorkGrade)}</b> completed work</span><span>Target: <b>{formatPercent(course.target.target)}</b></span></div>{course.target.target ? <p className="mt-2 text-xs text-muted-foreground">{course.target.standing === "achievable" ? `Required remaining average: ${formatPercent(course.target.requiredAverage)}` : course.target.standing === "already_secured" ? "Target already secured mathematically." : "Target is not currently possible with configured remaining work."}</p> : null}{next ? <p className="mt-3 text-xs"><b>Next:</b> {next.name} · {assessmentLocalDate(next, data.timezone)}</p> : null}</Link>; }) : data.term ? <p className="rounded-xl border border-dashed p-6 text-center text-sm text-muted-foreground sm:col-span-2">No courses in this term yet.</p> : null}</div></div>
      <div className={panel}><h2 className="font-bold">Upcoming workload</h2><p className="text-xs text-muted-foreground">Next 14 days</p><div className="mt-3 space-y-3">{data.upcoming.filter((assessment) => assessmentLocalDate(assessment, data.timezone) <= data.ranges.fourteen.end).slice(0, 6).map((assessment) => { const course = courseMap.get(assessment.course_id); const date = assessmentLocalDate(assessment, data.timezone); return <Link className="block rounded-lg border p-3" href={`/school/courses/${assessment.course_id}#assessment-${assessment.id}`} key={assessment.id}><p className="text-sm font-semibold">{course?.code} · {assessment.name}</p><p className="text-xs text-muted-foreground">{date} · {assessment.weight_percent}% · {daysUntilLabel(data.today, date)}</p></Link>; })}{!data.upcoming.length ? <p className="text-sm text-muted-foreground">No upcoming assessments.</p> : null}</div>{data.major[0] ? <div className="mt-5 border-t pt-4"><p className="text-xs font-bold uppercase tracking-wide text-muted-foreground">Next major assessment</p><p className="mt-1 font-semibold">{courseMap.get(data.major[0].course_id)?.code} · {data.major[0].name}</p><p className="text-xs text-muted-foreground">{assessmentLocalDate(data.major[0], data.timezone)}</p></div> : null}</div></section>

    <section className="grid gap-4 lg:grid-cols-2"><details className={panel} open={!data.terms.length}><summary className="cursor-pointer font-bold"><Plus className="mr-2 inline size-4" />Add or manage terms</summary><form action={saveTerm} className="mt-4 grid gap-3 sm:grid-cols-2"><label>Name<input className={input} name="name" required placeholder="Fall 2026" /></label><label>Academic year<input className={input} name="academicYear" /></label><label>Starts<input className={input} name="startDate" required type="date" /></label><label>Ends<input className={input} name="endDate" required type="date" /></label><button className="h-10 rounded-lg bg-primary text-sm font-semibold text-primary-foreground sm:col-span-2">Save term</button></form>{data.terms.map((term) => <div className="mt-3 flex items-center gap-2 border-t pt-3" key={term.id}><span className="flex-1 text-sm">{term.name}</span><form action={archiveSchoolEntity}><input name="id" type="hidden" value={term.id} /><input name="type" type="hidden" value="term" /><button className="text-xs font-semibold text-destructive">Archive</button></form></div>)}</details><details className={panel} open={Boolean(data.term) && !data.courses.length}><summary className="cursor-pointer font-bold"><BookOpen className="mr-2 inline size-4" />Add course</summary>{data.terms.length ? <form action={saveCourse} className="mt-4 grid gap-3 sm:grid-cols-2"><label>Term<select className={input} defaultValue={data.term?.id} name="termId">{data.terms.map((term) => <option key={term.id} value={term.id}>{term.name}</option>)}</select></label><label>Code<input className={input} name="code" required /></label><label className="sm:col-span-2">Name<input className={input} name="name" required /></label><label>Instructor<input className={input} name="instructor" /></label><label>Section<input className={input} name="section" /></label><label>Room<input className={input} name="location" /></label><label>Target %<input className={input} name="targetGrade" /></label><input name="courseUrl" type="hidden" /><input name="notes" type="hidden" /><label>Identity<select className={input} name="colorKey">{["plum", "blue", "teal", "amber", "rose", "slate"].map((value) => <option key={value}>{value}</option>)}</select></label><button className="h-10 rounded-lg bg-primary text-sm font-semibold text-primary-foreground sm:col-span-2">Create course</button></form> : <p className="mt-4 text-sm text-muted-foreground">Create a term first.</p>}</details></section>
    <p className="flex items-center gap-2 text-xs text-muted-foreground"><CalendarDays className="size-4" />Academic dates project into Calendar without duplicate rows.</p>
  </div>;
}
