import type { Metadata } from "next";
import Link from "next/link";
import { ArrowLeft, ExternalLink } from "lucide-react";

import { instantToLocalInput } from "@/features/calendar/dates";
import { addMeetings, archiveSchoolEntity, saveCourse, saveCourseResource, setMeetingActive } from "@/features/school/actions";
import { assessmentPercentage, exactToString, formatPercent } from "@/features/school/grades";
import { getCourseDetail, gradeRow } from "@/features/school/queries";
import { AssessmentForm, GradeTools } from "@/features/school/school-forms";
import { groupMeetingPatterns } from "@/features/school/planning";

export const metadata: Metadata = { title: "Course" };
const input = "mt-1 h-10 w-full rounded-lg border bg-card px-3 text-sm";
const panel = "rounded-2xl border bg-card p-5 shadow-sm";
const days = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];
function displayTime(value: string) { const [hour, minute] = value.split(":").map(Number); return `${hour % 12 || 12}:${String(minute).padStart(2, "0")} ${hour < 12 ? "AM" : "PM"}`; }

export default async function CoursePage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ error?: string; success?: string }> }) {
  const { id } = await params;
  const query = await searchParams;
  const data = await getCourseDetail(id);
  const grade = data.course.grade;
  const target = data.course.target;
  const ungraded = data.assessments.filter((assessment) => !["graded", "missed", "exempt"].includes(assessment.status)).map((assessment) => ({ id: assessment.id, name: assessment.name, weight: String(assessment.weight_percent) }));
  const nonExempt = data.assessments.filter((assessment) => assessment.status !== "exempt");
  const completed = nonExempt.filter((assessment) => ["submitted", "graded", "missed"].includes(assessment.status)).length;
  const meetingGroups = groupMeetingPatterns(data.meetings);

  return <div className="space-y-7">
    <Link className="inline-flex items-center gap-2 text-sm font-semibold text-primary" href="/school"><ArrowLeft className="size-4" />School</Link>
    {query.error ? <p className="rounded-lg bg-destructive/10 p-3 text-sm text-destructive">{query.error}</p> : null}
    {query.success ? <p className="rounded-lg bg-success/10 p-3 text-sm text-success">{query.success}</p> : null}
    <header><p className="text-sm font-semibold text-primary">{data.term?.name}</p><h1 className="text-3xl font-bold">{data.course.code} · {data.course.name}</h1><p className="text-sm text-muted-foreground">{data.course.instructor ?? "No instructor"}</p></header>

    <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["Completed-work grade", formatPercent(grade.completedWorkGrade)], ["Earned course points", formatPercent(grade.earnedCoursePoints)], ["Graded weight", formatPercent(grade.gradedWeight)], ["Remaining configured", formatPercent(grade.remainingConfiguredWeight)]].map(([label, value]) => <div className={panel} key={label}><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 text-2xl font-bold">{value}</p></div>)}</section>
    {grade.weightDelta !== 0n ? <p className="rounded-lg bg-accent/40 p-3 text-sm">{grade.weightDelta > 0n ? `${formatPercent(grade.weightDelta)} over 100% configured.` : `${formatPercent(-grade.weightDelta)} remains unconfigured.`}</p> : null}

    <section className={panel}><h2 className="text-lg font-bold">Target standing</h2>{target.target === null ? <p className="mt-2 text-sm text-muted-foreground">Set a target grade in Course settings to unlock target planning.</p> : <div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><div><p className="text-xs text-muted-foreground">Target</p><b>{formatPercent(target.target)}</b></div><div><p className="text-xs text-muted-foreground">Points still needed</p><b>{formatPercent(target.pointsStillNeeded)}</b></div><div><p className="text-xs text-muted-foreground">Required remaining average</p><b>{formatPercent(target.requiredAverage)}</b></div><div><p className="text-xs text-muted-foreground">Mathematical status</p><b>{target.standing === "already_secured" ? "Already secured" : target.standing === "impossible" || target.standing === "no_remaining" ? "Not currently possible" : "Achievable"}</b></div></div>}<p className="mt-3 text-xs text-muted-foreground">Based only on configured, non-exempt assessment weights. This is deterministic math, not a performance prediction.</p></section>

    <section className={panel}><h2 className="text-lg font-bold">Multi-assessment scenario</h2><p className="text-sm text-muted-foreground">Model all remaining assessments together or solve one while the others stay fixed.</p><div className="mt-4"><GradeTools assessments={ungraded} currentPoints={exactToString(grade.earnedCoursePoints)} target={data.course.target_grade === null ? null : String(data.course.target_grade)} /></div></section>

    <section className={panel}><h2 className="text-lg font-bold">Assessment progress</h2><p className="mt-2 text-2xl font-bold">{completed} of {nonExempt.length} handled</p><p className="text-sm text-muted-foreground">Submitted, graded, and missed assessments count as handled. Exempt work is excluded.</p></section>

    <section className={panel}>
      <h2 className="text-lg font-bold">Assessments</h2>
      <details className="my-4 rounded-xl border p-4"><summary className="cursor-pointer font-semibold">Add assessment</summary><div className="mt-4"><AssessmentForm courseId={id} /></div></details>
      <div className="space-y-3">{data.assessments.length ? data.assessments.map((assessment) => <article className="rounded-xl border p-4" id={`assessment-${assessment.id}`} key={assessment.id}>
        <div className="flex gap-3"><div className="flex-1"><p className="font-semibold">{assessment.name}</p><p className="text-xs capitalize text-muted-foreground">{assessment.assessment_type.replaceAll("_", " ")} · {assessment.weight_percent}% · {assessment.status}{assessment.estimated_effort_minutes ? ` · ${Math.round(assessment.estimated_effort_minutes / 6) / 10}h estimated` : ""}</p></div><b>{formatPercent(assessmentPercentage(gradeRow(assessment)))}</b></div>
        <details className="mt-3"><summary className="cursor-pointer text-xs font-semibold text-primary">Edit / record grade</summary><div className="mt-3"><AssessmentForm courseId={id} defaults={{ id: assessment.id, name: assessment.name, assessmentType: assessment.assessment_type, timingType: assessment.timing_type, dueLocal: assessment.due_at ? instantToLocalInput(assessment.due_at, data.timezone) : null, startsLocal: assessment.starts_at ? instantToLocalInput(assessment.starts_at, data.timezone) : null, endsLocal: assessment.ends_at ? instantToLocalInput(assessment.ends_at, data.timezone) : null, eventDate: assessment.event_date, weight: String(assessment.weight_percent), scoreEarned: assessment.score_earned === null ? null : String(assessment.score_earned), scoreMax: assessment.score_max === null ? null : String(assessment.score_max), effortHours: assessment.estimated_effort_minutes === null ? null : String(assessment.estimated_effort_minutes / 60), status: assessment.status, location: assessment.location, notes: assessment.notes }} /></div></details>
        <form action={archiveSchoolEntity} className="mt-2"><input name="id" type="hidden" value={assessment.id} /><input name="courseId" type="hidden" value={id} /><input name="type" type="hidden" value="assessment" /><button className="text-xs font-semibold text-destructive">Archive</button></form>
      </article>) : <p className="rounded-xl border border-dashed p-5 text-sm text-muted-foreground">No assessments yet. Add the grading breakdown when it is known.</p>}</div>
    </section>

    <section className={panel}>
      <h2 className="text-lg font-bold">Meeting schedule</h2>
      <details className="my-4 rounded-xl border p-4"><summary className="cursor-pointer font-semibold">Add meeting days</summary><form action={addMeetings} className="mt-3 grid gap-3 sm:grid-cols-2"><input name="courseId" type="hidden" value={id} /><label>Type<select className={input} name="meetingType">{["lecture", "tutorial", "lab", "seminar", "other"].map((value) => <option key={value}>{value}</option>)}</select></label><label>Location<input className={input} name="location" /></label><fieldset className="sm:col-span-2"><legend>Weekdays</legend>{days.map((day, weekday) => <label className="mr-3 text-sm" key={day}><input name="weekdays" type="checkbox" value={weekday} /> {day}</label>)}</fieldset><label>Starts<input className={input} name="startTime" required type="time" /></label><label>Ends<input className={input} name="endTime" required type="time" /></label><label>Effective start<input className={input} defaultValue={data.term?.start_date} name="effectiveStart" required type="date" /></label><label>Effective end<input className={input} defaultValue={data.term?.end_date} name="effectiveEnd" required type="date" /></label><button className="h-10 rounded-lg bg-primary font-semibold text-primary-foreground sm:col-span-2">Add selected days</button></form></details>
      {meetingGroups.length ? <div className="grid gap-3 sm:grid-cols-2">{meetingGroups.map((group) => <article className="rounded-xl border p-4" key={`${group.meetingType}-${group.startTime}-${group.weekdays.join("-")}`}><p className="text-xs font-bold uppercase tracking-wide text-primary">{group.meetingType}</p><p className="mt-1 font-semibold">{group.weekdays.map((weekday) => days[weekday]).join(" / ")}</p><p className="text-sm">{displayTime(group.startTime)} – {displayTime(group.endTime)}</p><p className="text-sm text-muted-foreground">{group.location ?? "No room"}</p><div className="mt-2 flex flex-wrap gap-2">{group.ids.map((meetingId, index) => <form action={setMeetingActive} key={meetingId}><input name="id" type="hidden" value={meetingId} /><input name="courseId" type="hidden" value={id} /><input name="active" type="hidden" value={String(!group.active)} /><button className="text-xs font-semibold text-primary">{group.active ? `Pause ${days[group.weekdays[index]]}` : `Resume ${days[group.weekdays[index]]}`}</button></form>)}</div></article>)}</div> : <p className="text-sm text-muted-foreground">No weekly meetings configured.</p>}
    </section>

    <section className={panel}><h2 className="text-lg font-bold">Course resources</h2><p className="text-sm text-muted-foreground">Useful links only; LifeStack is not storing or parsing documents yet.</p><div className="mt-4 grid gap-3 sm:grid-cols-2">{data.resources.map((resource) => <article className="rounded-xl border p-4" key={resource.id}><a className="flex items-center gap-2 font-semibold text-primary" href={resource.url} rel="noreferrer" target="_blank">{resource.label}<ExternalLink className="size-3.5" /></a><p className="text-xs capitalize text-muted-foreground">{resource.resource_type.replaceAll("_", " ")}</p><details className="mt-2"><summary className="cursor-pointer text-xs font-semibold">Edit</summary><form action={saveCourseResource} className="mt-3 grid gap-2"><input name="id" type="hidden" value={resource.id} /><input name="courseId" type="hidden" value={id} /><input className={input} defaultValue={resource.label} name="label" required /><input className={input} defaultValue={resource.url} name="url" required type="url" /><select className={input} defaultValue={resource.resource_type} name="resourceType">{["course_website", "lms", "syllabus", "textbook", "repository", "lecture_notes", "other"].map((value) => <option key={value} value={value}>{value.replaceAll("_", " ")}</option>)}</select><input name="sortOrder" type="hidden" value={resource.sort_order} /><button className="text-sm font-semibold text-primary">Save link</button></form></details><form action={archiveSchoolEntity} className="mt-2"><input name="id" type="hidden" value={resource.id} /><input name="courseId" type="hidden" value={id} /><input name="type" type="hidden" value="resource" /><button className="text-xs font-semibold text-destructive">Remove</button></form></article>)}</div><details className="mt-4 rounded-xl border p-4"><summary className="cursor-pointer font-semibold">Add resource</summary><form action={saveCourseResource} className="mt-3 grid gap-3 sm:grid-cols-2"><input name="courseId" type="hidden" value={id} /><label>Label<input className={input} name="label" required placeholder="Course website" /></label><label>URL<input className={input} name="url" required type="url" placeholder="https://" /></label><label>Type<select className={input} name="resourceType">{["course_website", "lms", "syllabus", "textbook", "repository", "lecture_notes", "other"].map((value) => <option key={value} value={value}>{value.replaceAll("_", " ")}</option>)}</select></label><label>Order<input className={input} defaultValue="0" min="0" name="sortOrder" type="number" /></label><button className="h-10 rounded-lg bg-primary font-semibold text-primary-foreground sm:col-span-2">Add resource</button></form></details></section>

    <section className={panel}><details><summary className="cursor-pointer text-lg font-bold">Course settings</summary><form action={saveCourse} className="mt-4 grid gap-3 sm:grid-cols-2"><input name="id" type="hidden" value={id} /><label>Term<select className={input} defaultValue={data.course.term_id} name="termId">{data.terms.map((term) => <option key={term.id} value={term.id}>{term.name}</option>)}</select></label><label>Code<input className={input} defaultValue={data.course.code} name="code" required /></label><label className="sm:col-span-2">Name<input className={input} defaultValue={data.course.name} name="name" required /></label><label>Instructor<input className={input} defaultValue={data.course.instructor ?? ""} name="instructor" /></label><label>Section<input className={input} defaultValue={data.course.section ?? ""} name="section" /></label><label>Room<input className={input} defaultValue={data.course.location ?? ""} name="location" /></label><label>Target %<input className={input} defaultValue={data.course.target_grade ?? ""} name="targetGrade" /></label><label>Course URL<input className={input} defaultValue={data.course.course_url ?? ""} name="courseUrl" type="url" /></label><label>Identity<select className={input} defaultValue={data.course.color_key} name="colorKey">{["plum", "blue", "teal", "amber", "rose", "slate"].map((value) => <option key={value}>{value}</option>)}</select></label><label className="sm:col-span-2">Notes<textarea className="mt-1 min-h-20 w-full rounded-lg border bg-card p-3" defaultValue={data.course.notes ?? ""} name="notes" /></label><button className="h-10 rounded-lg bg-primary font-semibold text-primary-foreground sm:col-span-2">Save course</button></form><form action={archiveSchoolEntity} className="mt-4"><input name="id" type="hidden" value={id} /><input name="type" type="hidden" value="course" /><button className="text-sm font-semibold text-destructive">Archive course and hide its projections</button></form></details></section>
  </div>;
}
