import Link from "next/link";
import { AssessmentPerformanceChart } from "@/features/analytics/analytics-charts";
import { getSchoolDeepAnalytics } from "@/features/analytics/deep-service";
import { AnalyticsRangeControls, AnalyticsSectionNav } from "@/features/analytics/range-controls";
import { formatPercent, parseExact } from "@/features/school/grades";

export const metadata = { title: "School Analytics" };
const panel = "rounded-2xl border bg-card p-5 shadow-sm sm:p-6"; type Query = { range?: string | string[]; from?: string | string[]; to?: string | string[] };
const typeLabel = (value: string) => value.replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase());
const targetLabel: Record<string, string> = { missing_target: "No target", achievable: "Achievable", already_secured: "Secured", impossible: "Impossible with configured work", no_remaining: "No remaining configured work" };

export default async function SchoolAnalyticsPage({ searchParams }: { searchParams: Promise<Query> }) {
  const data = await getSchoolDeepAnalytics(await searchParams);
  return <div className="space-y-7"><header><Link className="text-sm font-semibold text-primary" href="/analytics">← Analytics overview</Link><h1 className="mt-2 text-3xl font-bold">School analytics</h1><p className="mt-2 text-sm text-muted-foreground">Exact assessment performance, current course standing, and workload—never a fabricated GPA.</p></header><AnalyticsSectionNav active="school"/><AnalyticsRangeControls basePath="/analytics/school" range={data.range} selection={data.rangeSelection} timeZone={data.timeZone}/>
    <section className="grid gap-3 sm:grid-cols-3 lg:grid-cols-6">{[["Assessments",data.due],["Completed",data.completed],["Graded",data.graded],["Missed",data.missed],["Exempt",data.exempt],["Estimated effort",`${data.effortMinutes} min`]].map(([label,value]) => <article className="rounded-xl border bg-card p-4" key={label}><p className="text-xs font-bold uppercase text-muted-foreground">{label}</p><p className="mt-2 text-2xl font-bold">{value}</p></article>)}</section>
    <section className={panel}><h2 className="text-xl font-bold">Assessment performance</h2><p className="text-sm text-muted-foreground">Chronological earned ÷ maximum results. Missed work is zero; exempt work is omitted.</p><AssessmentPerformanceChart data={data.timeline}/>{data.timeline.length ? <div className="mt-3 max-h-72 overflow-y-auto divide-y rounded-xl border">{data.timeline.map((item) => <Link className="grid gap-1 p-3 text-sm hover:bg-muted/40 sm:grid-cols-[auto_1fr_auto] sm:gap-3" href={`/school/courses/${item.courseId}#assessment-${item.id}`} key={item.id}><span>{item.date}</span><span className="min-w-0"><strong>{item.courseCode}</strong> · {item.name}</span><strong>{formatPercent(parseExact(item.percentage))}{item.status === "missed" ? " · Missed" : ""}</strong></Link>)}</div> : null}</section>
    <section className={panel}><div className="flex justify-between gap-3"><div><h2 className="text-xl font-bold">Current course standing</h2><p className="text-sm text-muted-foreground">Authoritative School grade and target calculations.</p></div><Link className="text-sm font-semibold text-primary" href="/school/planning">School planning</Link></div>{data.courseStandings.length ? <div className="mt-4 grid gap-4 lg:grid-cols-2">{data.courseStandings.map((course) => <Link className="rounded-xl border p-4 hover:border-primary/40" href={`/school/courses/${course.id}`} key={course.id}><h3 className="font-bold">{course.code} · {course.name}</h3><div className="mt-3 grid grid-cols-2 gap-2 text-sm"><p>Completed-work grade<br/><strong>{course.completedWorkGrade ? formatPercent(parseExact(course.completedWorkGrade)) : "Not enough data"}</strong></p><p>Earned course points<br/><strong>{formatPercent(parseExact(course.earnedCoursePoints))}</strong></p><p>Graded weight<br/><strong>{formatPercent(parseExact(course.gradedWeight))}</strong></p><p>Remaining configured<br/><strong>{formatPercent(parseExact(course.remainingConfiguredWeight))}</strong></p><p>Target<br/><strong>{course.target ? formatPercent(parseExact(course.target)) : "Not set"}</strong></p><p>Required remaining average<br/><strong>{course.requiredAverage ? formatPercent(parseExact(course.requiredAverage)) : "Not available"}</strong></p></div><p className="mt-3 text-sm font-semibold">Target state: {targetLabel[course.targetState] ?? course.targetState}</p><p className="mt-2 text-xs text-muted-foreground">{course.statuses.map((item) => `${item.status}: ${item.count}`).join(" · ")}</p></Link>)}</div> : <p className="mt-4 text-sm text-muted-foreground">No active courses.</p>}</section>
    <section className={panel}><h2 className="text-xl font-bold">Assessment types and workload</h2><p className="text-sm text-muted-foreground">Type averages are unweighted assessment-result averages with sample counts; course standing remains authoritative.</p>{data.byType.length ? <div className="mt-4 overflow-x-auto"><table className="w-full min-w-[650px] text-left text-sm"><thead className="text-xs uppercase text-muted-foreground"><tr><th>Type</th><th>Assessments</th><th>Result samples</th><th>Average result</th><th>Configured weight</th><th>Effort coverage</th></tr></thead><tbody>{data.byType.map((item) => <tr className="border-t" key={item.type}><td className="py-3 font-semibold">{typeLabel(item.type)}</td><td>{item.assessments}</td><td>{item.sampleCount}</td><td>{item.averagePercent ? formatPercent(parseExact(item.averagePercent)) : "Not enough data"}</td><td>{formatPercent(parseExact(item.configuredWeight))}</td><td>{item.effortMinutes} min across {item.effortCount}</td></tr>)}</tbody></table></div> : <p className="mt-4 text-sm text-muted-foreground">No assessment workload in this range.</p>}</section>
  </div>;
}
