import Link from "next/link";
import { getGoalDeepAnalytics } from "@/features/analytics/deep-service";
import { AnalyticsRangeControls, AnalyticsSectionNav } from "@/features/analytics/range-controls";

export const metadata = { title: "Goal Analytics" };
const panel = "rounded-2xl border bg-card p-5 shadow-sm sm:p-6"; type Query = { range?: string | string[]; from?: string | string[]; to?: string | string[] };

export default async function GoalAnalyticsPage({ searchParams }: { searchParams: Promise<Query> }) {
  const data = await getGoalDeepAnalytics(await searchParams);
  return <div className="space-y-7"><header><Link className="text-sm font-semibold text-primary" href="/analytics">← Analytics overview</Link><h1 className="mt-2 text-3xl font-bold">Goal analytics</h1><p className="mt-2 text-sm text-muted-foreground">Current authoritative progress, completion events, deadlines, and category coverage—without invented history.</p></header><AnalyticsSectionNav active="goals"/><AnalyticsRangeControls basePath="/analytics/goals" range={data.range} selection={data.rangeSelection} timeZone={data.timeZone}/>
    <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["Active",data.active],["Completed total",data.completedTotal],["Completed in range",data.completedInRange],["Overdue active",data.overdue]].map(([label,value]) => <article className="rounded-xl border bg-card p-4" key={label}><p className="text-xs font-bold uppercase text-muted-foreground">{label}</p><p className="mt-2 text-2xl font-bold">{value}</p></article>)}</section>
    <section className={panel}><div className="flex justify-between gap-3"><div><h2 className="text-xl font-bold">Current Goal progress</h2><p className="text-sm text-muted-foreground">Bars cap visually at 100%; the authoritative text preserves over-target values.</p></div><Link className="text-sm font-semibold text-primary" href="/goals">View Goals</Link></div>{data.items.length ? <div className="mt-4 grid gap-3 lg:grid-cols-2">{data.items.map((goal) => { const display = Math.max(0, Math.min(100, Number(goal.progressPercent ?? 0))); const deadlineState = goal.status === "active" && goal.deadline && goal.deadline < data.today ? "Overdue" : goal.deadline ? `Due ${goal.deadline}` : "No deadline"; return <Link className="rounded-xl border p-4 hover:border-primary/40" href={`/goals/${goal.id}`} key={goal.id}><div className="flex justify-between gap-3"><div><h3 className="font-bold">{goal.title}</h3><p className="text-xs text-muted-foreground">{goal.category.replaceAll("_"," ")} · {deadlineState}</p></div><span className="text-xs font-semibold capitalize">{goal.status}</span></div>{goal.progressPercent !== null ? <><div className="mt-3 h-2 overflow-hidden rounded-full bg-muted" aria-hidden="true"><div className="h-full bg-primary" style={{ width: `${display}%` }}/></div><p className="mt-2 text-sm font-semibold">{goal.progressLabel}{goal.overTarget ? " · Above target" : ""}</p></> : <p className="mt-3 text-sm text-muted-foreground">Unmeasured Goal</p>}</Link>; })}</div> : <p className="mt-4 text-sm text-muted-foreground">No Goals yet.</p>}</section>
    <section className={panel}><h2 className="text-xl font-bold">Category distribution</h2><p className="text-sm text-muted-foreground">Current visible Goals and deadlines due within the next 30 days.</p>{data.categories.length ? <div className="mt-4 overflow-x-auto"><table className="w-full min-w-[500px] text-left text-sm"><thead className="text-xs uppercase text-muted-foreground"><tr><th>Category</th><th>Active</th><th>Completed</th><th>Upcoming deadlines</th></tr></thead><tbody>{data.categories.map((item) => <tr className="border-t" key={item.category}><td className="py-3 font-semibold">{item.label}</td><td>{item.active}</td><td>{item.completed}</td><td>{item.upcoming}</td></tr>)}</tbody></table></div> : <p className="mt-4 text-sm text-muted-foreground">Not enough Goal data yet.</p>}</section>
    <section className="rounded-xl border border-dashed p-5 text-sm text-muted-foreground"><strong className="text-foreground">Progress history is intentionally unavailable.</strong> LifeStack stores current Goal progress, not historical snapshots, so this page does not fabricate a progress-over-time or staleness trend. Current coverage: {data.measured} measured and {data.unmeasured} unmeasured Goals; {data.upcoming} active deadlines are approaching.</section>
  </div>;
}
